//
//  DiscImageNames.swift
//  DiscGolfSearch
//
//  Created by Kinney Kare on 9/22/23.
//

import Foundation

struct DiscImageNames {
    // Define a dictionary to store companies and their discs
    static let companies: [String: [String: String]] = [
        "Infinite Discs": [
            "alpaca":"https://imagizer.imageshack.com/img922/2418/W4XnJX.png",
            "anubis":"https://imagizer.imageshack.com/img924/569/6gvgVj.png",
            "aztec":"https://imagizer.imageshack.com/img924/489/fdCE7i.png",
            "centurion":"https://imagizer.imageshack.com/img922/602/3pJnG2.png",
            "chariot":"https://imagizer.imageshack.com/img924/1542/RoGDvm.png",
            "cohort":"https://imagizer.imageshack.com/img922/9666/Ak1jNE.png",
            "czar":"https://imagizer.imageshack.com/img924/8859/84mD5T.png",
            "dynasty":"https://imagizer.imageshack.com/img923/9766/0t41Vh.png",
            "emperor":"https://imagizer.imageshack.com/img924/5829/ouXTOV.png",
            "exodus":"https://imagizer.imageshack.com/img922/8889/RXhTha.png",
            "inca":"https://imagizer.imageshack.com/img924/8210/P1sD67.png",
            "kon-tiki":"https://imagizer.imageshack.com/img923/3780/HFvN78.png",
            "maya":"https://imagizer.imageshack.com/img924/1162/UINUNz.png",
            "myth":"https://imagizer.imageshack.com/img922/7906/7Z1wJA.png",
            "pharaoh":"https://imagizer.imageshack.com/img923/760/mg7Yh3.png",
            "ra":"https://imagizer.imageshack.com/img924/4161/zJZSif.png",
            "raze":"https://imagizer.imageshack.com/img923/2397/2Wvz4q.png",
            "roman":"https://imagizer.imageshack.com/img922/3958/eJWrOj.png",
            "ruin":"https://imagizer.imageshack.com/img923/356/nK5Nz4.png",
            "scarab":"https://imagizer.imageshack.com/img922/4884/9Wl2sJ.png",
            "scepter":"https://imagizer.imageshack.com/img923/8964/5dyKvb.png",
            "slab":"https://imagizer.imageshack.com/img923/7360/PN9WrL.png",
            "sphinx":"https://imagizer.imageshack.com/img924/1486/hc35ay.png",
            "tomb":"https://imagizer.imageshack.com/img923/2565/D6iEz4.png"
        ],
        "Clash Discs": [
            "berry":"https://imagizer.imageshack.com/img923/5803/JXm0hI.png",
            "butter":"https://imagizer.imageshack.com/img923/2118/XJ9OH5.png",
            "candy":"https://imagizer.imageshack.com/img924/6928/xQVmwc.png",
            "cinnamon":"https://imagizer.imageshack.com/img922/4460/mkfiBE.png",
            "cookie":"https://imagizer.imageshack.com/img923/4878/2LHpS1.png",
            "fudge":"https://imagizer.imageshack.com/img924/1483/wzZaLM.png",
            "ginger":"https://imagizer.imageshack.com/img922/3230/tzqKYG.png",
            "honey":"https://imagizer.imageshack.com/img922/2686/7AOE9f.png",
            "lotus":"https://imagizer.imageshack.com/img923/5320/pxwCew.png",
            "mango":"https://imagizer.imageshack.com/img924/504/E1QZ7i.png",
            "mint":"https://imagizer.imageshack.com/img923/2961/y0Mjh9.png",
            "peach":"https://imagizer.imageshack.com/img922/4282/geLTCt.png",
            "pepper":"https://imagizer.imageshack.com/img924/5648/cycXGB.png",
            "peppermint":"https://imagizer.imageshack.com/img922/3672/bX2TfD.png",
            "popcorn":"https://imagizer.imageshack.com/img923/2786/jiQZh9.png",
            "salt":"https://imagizer.imageshack.com/img924/3793/AznhrS.png",
            "soda":"https://imagizer.imageshack.com/img922/1124/M786QV.png",
            "spice":"https://imagizer.imageshack.com/img923/2144/q8Dizc.png",
            "vanilla":"https://imagizer.imageshack.com/img924/3615/Zgv8sp.png"
        ],
        "RPM": [
            "huia":"https://imagizer.imageshack.com/img923/8006/XGT1WV.png",
            "kahu":"https://imagizer.imageshack.com/img924/1383/U9St36.png",
            "kahu-os":"https://imagizer.imageshack.com/img923/3046/VyDnfE.png",
            "kahu-xg":"https://imagizer.imageshack.com/img922/3668/gdeMZc.png",
            "kea":"https://imagizer.imageshack.com/img923/1584/iyWRnY.png",
            "kiwi":"https://imagizer.imageshack.com/img924/1431/XCIfhc.png",
            "kotare":"https://imagizer.imageshack.com/img922/2058/mmhfoX.png",
            "kotuku":"https://imagizer.imageshack.com/img924/9471/YLcC3m.png",
            "pekapeka":"https://imagizer.imageshack.com/img923/1161/bgMfwF.png",
            "piwakawaka":"https://imagizer.imageshack.com/img923/7626/3Au62q.png",
            "ruru":"https://imagizer.imageshack.com/img922/8006/EXIVz8.png",
            "takapu":"https://imagizer.imageshack.com/img922/782/CTmoG2.png",
            "taniwha":"https://imagizer.imageshack.com/img924/6487/Rg4NMW.png",
            "tara-iti":"https://imagizer.imageshack.com/img922/9352/luZ6bd.png",
            "tui":"https://imagizer.imageshack.com/img922/9427/jvGizj.png"
        ],
        "DGA":  [
            "aftershock": "https://imagizer.imageshack.com/img922/4298/M8qfkC.png",
            "avalanche": "https://imagizer.imageshack.com/img924/8675/ADPLaK.png",
            "banzai": "https://imagizer.imageshack.com/img923/5310/IY5HXR.png",
            "blowfly": "https://imagizer.imageshack.com/img922/2730/E3Lxg8.png",
            "breaker": "https://imagizer.imageshack.com/img922/6444/vN4q9z.png",
            "gumbputt": "https://imagizer.imageshack.com/img923/9821/RHNyLS.png",
            "hellfire": "https://imagizer.imageshack.com/img924/4411/VEhQaw.png",
            "hurricane": "https://imagizer.imageshack.com/img923/1766/QhT9rR.png",
            "hypercane": "https://imagizer.imageshack.com/img924/8861/svfkvU.png",
            "pipeline": "https://imagizer.imageshack.com/img922/4491/0snXl3.png",
            "quake": "https://imagizer.imageshack.com/img923/3569/rgzpnn.png",
            "reef": "https://imagizer.imageshack.com/img923/8649/dzub94.png",
            "rift": "https://imagizer.imageshack.com/img922/8803/aRkS82.png",
            "riptide": "https://imagizer.imageshack.com/img922/2739/s1MZjs.png",
            "rogue": "https://imagizer.imageshack.com/img922/627/sQBt3Q.png",
            "sail": "https://imagizer.imageshack.com/img924/9341/4PgQaG.png",
            "shockwave": "https://imagizer.imageshack.com/img924/661/H2c8T1.png",
            "squall": "https://imagizer.imageshack.com/img922/5866/TuJMWm.png",
            "steady": "https://imagizer.imageshack.com/img924/8873/oIce1F.png",
            "steady-bl": "https://imagizer.imageshack.com/img922/7596/4rvYsL.png",
            "tempest": "https://imagizer.imageshack.com/img923/8900/5pgeZf.png",
            "titanic": "https://imagizer.imageshack.com/img922/1954/dxRCMi.png",
            "torrent": "https://imagizer.imageshack.com/img923/7277/wScCAI.png",
            "tremor": "https://imagizer.imageshack.com/img922/7624/XMPh1i.png",
            "tsunami": "https://imagizer.imageshack.com/img924/7311/JZymUp.png",
            "undertow": "https://imagizer.imageshack.com/img923/47/jCxpW1.png",
            "vortex": "https://imagizer.imageshack.com/img923/8645/5lUFGX.png"
        ],
        "Daredevil Discs": [
            "albatross": "https://imagizer.imageshack.com/img922/6216/KhH4UL.png",
            "beaver":"https://imagizer.imageshack.com/img922/9844/6J23iU.png",
            "big-horn":"https://imagizer.imageshack.com/img924/4267/coHrxA.png",
            "bigfoot": "https://imagizer.imageshack.com/img923/3521/2yv4Bj.png",
            "buffalo": "https://imagizer.imageshack.com/img922/3960/wlO8Os.png",
            "caribou": "https://imagizer.imageshack.com/img922/2001/ghybHW.png",
            "grizzly": "https://imagizer.imageshack.com/img924/3977/2xtm2y.png",
            "hellbender": "https://imagizer.imageshack.com/img922/4960/Wvhwkg.png",
            "hellbender-razorback": "https://imagizer.imageshack.com/img923/8267/cTH1zJ.png",
            "mammoth": "https://imagizer.imageshack.com/img923/6462/ql4ggG.png",
            "merlin": "https://imagizer.imageshack.com/img923/3097/C2R47m.png",
            "moose": "https://imagizer.imageshack.com/img923/1347/qtJ3pC.png",
            "ogopogo": "https://imagizer.imageshack.com/img924/4199/pZ3g7y.png",
            "owl": "https://imagizer.imageshack.com/img922/7885/SCYYfi.png",
            "polar-bear":"https://imagizer.imageshack.com/img922/7521/f5A3nF.png",
            "sabertooth": "https://imagizer.imageshack.com/img924/7082/XeRb3T.png",
            "sasquatch": "https://imagizer.imageshack.com/img923/7936/AiFf08.png",
            "swift-fox": "https://imagizer.imageshack.com/img924/3926/F4Hdly.png",
            "timberwolf": "https://imagizer.imageshack.com/img923/898/pjDxB7.png",
            "walrus": "https://imagizer.imageshack.com/img924/9999/RTq8b1.png",
            "woodchuck":"https://imagizer.imageshack.com/img922/9278/YqSyOa.png",
            "wolverine": "https://imagizer.imageshack.com/img923/4229/sbbUsU.png",
            "yeti": "https://imagizer.imageshack.com/img924/111/lXDVot.png"
        ],
        "MVP": [
            "amp":"https://imagizer.imageshack.com/img923/7793/NMJG1J.png",
            "anode":"https://imagizer.imageshack.com/img923/9620/lbTfhi.png",
            "atom":"https://imagizer.imageshack.com/img924/1291/Ur8hBX.png",
            "axis":"https://imagizer.imageshack.com/img924/6828/UunWXA.png",
            "catalyst":"https://imagizer.imageshack.com/img922/9349/MZKyq4.png",
            "deflector":"https://imagizer.imageshack.com/img923/7343/4rPXsb.png",
            "dimension": "https://imagizer.imageshack.com/img924/2016/rd5ZYs.png",
            "energy": "https://imagizer.imageshack.com/img923/221/fwoGl8.png",
            "entropy": "https://imagizer.imageshack.com/img922/1640/uAji3L.png",
            "glitch": "https://imagizer.imageshack.com/img923/2356/REWapR.png",
            "impulse": "https://imagizer.imageshack.com/img922/6382/AJk1y6.png",
            "inertia": "https://imagizer.imageshack.com/img924/2009/X0w3yv.png",
            "ion": "https://imagizer.imageshack.com/img922/9325/G72xge.png",
            "limit": "https://imagizer.imageshack.com/img924/3819/pHFwQU.png",
            "matrix": "https://imagizer.imageshack.com/img922/4230/Q7hcYW.png",
            "motion": "https://imagizer.imageshack.com/img923/7729/roRwfH.png",
            "nitro": "https://imagizer.imageshack.com/img922/897/zFLMVI.png",
            "nomad": "https://imagizer.imageshack.com/img922/4165/oMweKX.png",
            "octane": "https://imagizer.imageshack.com/img924/8477/TIY5y3.png",
            "ohm": "https://imagizer.imageshack.com/img922/7348/nz7xdp.png",
            "orbital": "https://imagizer.imageshack.com/img924/7783/ZSU3M3.png",
            "particle": "https://imagizer.imageshack.com/img922/8858/so9Ssr.png",
            "phase": "https://imagizer.imageshack.com/img924/9431/fFBXoj.png",
            "photon": "https://imagizer.imageshack.com/img924/316/BEao0h.png",
            "reactor": "https://imagizer.imageshack.com/img923/8305/iU7Nyh.png",
            "relativity": "https://imagizer.imageshack.com/img923/7239/EVqh7c.png",
            "relay": "https://imagizer.imageshack.com/img924/1571/sU5ePa.png",
            "resistor": "https://imagizer.imageshack.com/img924/9327/KnHxRw.png",
            "servo": "https://imagizer.imageshack.com/img922/6669/isUVi3.png",
            "shock": "https://imagizer.imageshack.com/img924/9881/q6Lk0b.png",
            "signal": "https://imagizer.imageshack.com/img922/7793/vup7OG.png",
            "spin": "https://imagizer.imageshack.com/img924/8111/sH7v02.png",
            "switch": "https://imagizer.imageshack.com/img922/9646/boMJsC.png",
            "tangent": "https://imagizer.imageshack.com/img922/6560/VBpLpn.png",
            "teleport": "https://imagizer.imageshack.com/img923/2770/iNAFuP.png",
            "tensor": "https://imagizer.imageshack.com/img923/4442/UPu9nV.png",
            "terra": "https://imagizer.imageshack.com/img924/6991/vXp0Qk.png",
            "terra-electron": "https://imagizer.imageshack.com/img922/6120/0oAz4G.png",
            "tesla": "https://imagizer.imageshack.com/img923/2711/oEPrE1.png",
            "uplink": "https://imagizer.imageshack.com/img923/1542/lVOGDx.png",
            "vector": "https://imagizer.imageshack.com/img924/3513/t5doeZ.png",
            "vertex": "https://imagizer.imageshack.com/img922/7800/evZRqr.png",
            "volt":"https://imagizer.imageshack.com/img923/3183/l4JY1G.png",
            "watt": "https://imagizer.imageshack.com/img924/788/mG7JXA.png",
            "wave": "https://imagizer.imageshack.com/img923/562/2DksW7.png",
            "zenith": "https://imagizer.imageshack.com/img922/5575/x8cwQF.png"
        ],
        "Disc Golf UK": [
            "the-baron":"https://imagizer.imageshack.com/img923/3848/IQpwxK.png",
            "the-count":"https://imagizer.imageshack.com/img923/4467/w4FLdD.png",
            "the-duchess":"https://imagizer.imageshack.com/img924/6622/BUHa1i.png",
            "the-duke":"https://imagizer.imageshack.com/img922/534/DsbUJ5.png"
   
        ],
        "Elevation Disc Golf": [
            "arowana": "https://imagizer.imageshack.com/img924/4883/GF6Pl4.png",
            "binx-newcomer": "https://imagizer.imageshack.com/img922/2891/L7YI4G.png",
            "binx-ecoflex": "https://imagizer.imageshack.com/img922/7968/YKJtWy.png",
            "gecko":"https://imagizer.imageshack.com/img923/8159/ARWYIi.png",
            "interceptor":"https://imagizer.imageshack.com/img924/1706/MXlB3l.png",
            "koi":"https://imagizer.imageshack.com/img922/9048/PvEieo.png",
            "og-binx":"https://imagizer.imageshack.com/img924/2774/W0CrQA.png"
        ],
        "Axiom Discs": [
            "alias": "https://imagizer.imageshack.com/img923/726/5mtKlo.png",
            "clash": "https://imagizer.imageshack.com/img924/7365/EHNyhQ.png",
            "crave": "https://imagizer.imageshack.com/img922/8097/g4OQSN.png",
            "defy": "https://imagizer.imageshack.com/img923/3268/jEv4Cg.png",
            "delirium": "https://imagizer.imageshack.com/img924/2766/QiBcWc.png",
            "envy": "https://imagizer.imageshack.com/img922/1839/tgDBcT.png",
            "excite": "https://imagizer.imageshack.com/img923/8893/u8hfsP.png",
            "fireball": "https://imagizer.imageshack.com/img924/4710/OLgqJD.png",
            "hex": "https://imagizer.imageshack.com/img923/7524/RBmBto.png",
            "insanity": "https://imagizer.imageshack.com/img922/3973/AUK8m9.png",
            "inspire": "https://imagizer.imageshack.com/img924/2379/sWPrWT.png",
            "mayhem": "https://imagizer.imageshack.com/img923/7942/cydYAN.png",
            "panic": "https://imagizer.imageshack.com/img924/1356/eGYRlQ.png",
            "paradox": "https://imagizer.imageshack.com/img924/4989/VgyJcX.png",
            "proxy": "https://imagizer.imageshack.com/img924/9734/78aw2Q.png",
            "pyro": "https://imagizer.imageshack.com/img923/3528/xrM6kl.png",
            "rhythm": "https://imagizer.imageshack.com/img924/7606/4RxPE9.png",
            "tantrum": "https://imagizer.imageshack.com/img922/5659/e5jKEb.png",
            "tenacity": "https://imagizer.imageshack.com/img922/5341/weBfDz.png",
            "theory": "https://imagizer.imageshack.com/img923/5718/FTfyST.png",
            "thrill": "https://imagizer.imageshack.com/img924/6371/JmHufU.png",
            "time-lapse": "https://imagizer.imageshack.com/img922/9382/yIaI0T.png",
            "trance": "https://imagizer.imageshack.com/img923/7818/KbQyC3.png",
            "vanish": "https://imagizer.imageshack.com/img924/9472/NZeDFs.png",
            "virus": "https://imagizer.imageshack.com/img922/9262/bZ3pMN.png",
            "wrath": "https://imagizer.imageshack.com/img923/6576/i5hC2u.png"
        ],
        "Streamline": [
            "ascend": "https://imagizer.imageshack.com/img924/7803/If3tG5.png",
            "drift": "https://imagizer.imageshack.com/img923/1438/dWA93n.png",
            "echo": "https://imagizer.imageshack.com/img924/939/X4d21e.png",
            "electron-stabilizer": "https://imagizer.imageshack.com/img923/1893/YtUJtQ.png",
            "flare": "https://imagizer.imageshack.com/img924/9138/75m6GD.png",
            "jet": "https://imagizer.imageshack.com/img922/300/e8UKPD.png",
            "lift": "https://imagizer.imageshack.com/img924/8975/gH2cvS.png",
            "pilot": "https://imagizer.imageshack.com/img922/2904/03YVFC.png",
            "runway": "https://imagizer.imageshack.com/img923/8770/RS3cAp.png",
            "stabilizer": "https://imagizer.imageshack.com/img924/7586/AzfXIs.png",
            "trace": "https://imagizer.imageshack.com/img924/7531/vbl4Vh.png"
        ],
        "Dynamic Discs": [
            "agent": "https://imagizer.imageshack.com/img922/9760/IdgvQE.png",
            "bounty": "https://imagizer.imageshack.com/img922/5261/57HwyG.png",
            "breakout": "https://imagizer.imageshack.com/img923/5835/OdFdLH.png",
            "captain": "https://imagizer.imageshack.com/img923/8982/Y355TK.png",
            "convict": "https://imagizer.imageshack.com/img922/594/FAQ7cs.png",
            "criminal": "https://imagizer.imageshack.com/img923/1741/FNtwAq.png",
            "culprit": "https://imagizer.imageshack.com/img922/6107/xFdOSM.png",
            "defender": "https://imagizer.imageshack.com/img922/8490/osMRhL.png",
            "deputy": "https://imagizer.imageshack.com/img923/947/lqJ3IA.png",
            "emac-judge": "https://imagizer.imageshack.com/img922/598/KbrwEw.png",
            "enforcer": "https://imagizer.imageshack.com/img922/7573/vSX5wl.png",
            "escape": "https://imagizer.imageshack.com/img922/2110/suPSxI.png",
            "evader": "https://imagizer.imageshack.com/img924/6098/rAjLVG.png",
            "evidence": "https://imagizer.imageshack.com/img922/9233/CNbAnA.png",
            "felon": "https://imagizer.imageshack.com/img922/4655/A8RA6J.png",
            "freedom": "https://imagizer.imageshack.com/img924/7923/wPoBeC.png",
            "fugitive": "https://imagizer.imageshack.com/img923/1899/F4g2n3.png",
            "fugitive-supreme": "https://imagizer.imageshack.com/img924/1209/WsxYXs.png",
            "gavel": "https://imagizer.imageshack.com/img922/5351/1fgOIy.png",
            "getaway": "https://imagizer.imageshack.com/img924/8742/OLBVWh.png",
            "guard": "https://imagizer.imageshack.com/img924/5941/VWgT7c.png",
            "judge": "https://imagizer.imageshack.com/img923/6577/fHTN6k.png",
            "justice": "https://imagizer.imageshack.com/img923/9500/PXPZJI.png",
            "marshal": "https://imagizer.imageshack.com/img924/2291/MlhBaB.png",
            "maverick": "https://imagizer.imageshack.com/img923/508/1v5HjD.png",
            "patrol": "https://imagizer.imageshack.com/img923/846/C28xPm.png",
            "proof": "https://imagizer.imageshack.com/img922/2803/4QoIFp.png",
            "raider": "https://imagizer.imageshack.com/img923/7669/7NELa4.png",
            "renegade": "https://imagizer.imageshack.com/img922/9339/lnaN01.png",
            "sergeant": "https://imagizer.imageshack.com/img923/4144/yNvdLA.png",
            "sheriff": "https://imagizer.imageshack.com/img923/3054/PRCX9x.png",
            "slammer": "https://imagizer.imageshack.com/img922/1368/vXSV7y.png",
            "sockibomb-felon": "https://imagizer.imageshack.com/img924/707/CwZlR8.png",
            "sockibomb-slammer": "https://imagizer.imageshack.com/img922/9163/PQyHlE.png",
            "supreme-trespass": "https://imagizer.imageshack.com/img923/1792/OxLHpT.png",
            "suspect": "https://imagizer.imageshack.com/img923/8797/vo2vbD.png",
            "thief": "https://imagizer.imageshack.com/img922/3396/GPSNZv.png",
            "trespass": "https://imagizer.imageshack.com/img923/8594/1HcakT.png",
            "truth": "https://imagizer.imageshack.com/img922/9629/2M4QQP.png",
            "truth-emac": "https://imagizer.imageshack.com/img923/297/eED3Ik.png",
            "vandal": "https://imagizer.imageshack.com/img922/8386/RcCaPe.png",
            "verdict": "https://imagizer.imageshack.com/img924/2037/2n0f6r.png",
            "warant": "https://imagizer.imageshack.com/img924/4310/SiHyeQ.png",
            "warden": "https://imagizer.imageshack.com/img924/3586/iI6Wfn.png",
            "witness": "https://imagizer.imageshack.com/img922/6041/OmdsaK.png"
        ],
        "Co3": [
            "disc1": "https://example.com/co3/disc1",
            "disc2": "https://example.com/co3/disc2",
            "sharedDisc": "https://example.com/co3/sharedDisc"
        ]
    ]
    
    static func webLink(for company: String, disc: String) -> String? {
        return companies[company]?[disc]
    }
}

