//
//  DiscImageNames.swift
//  DiscGolfSearch
//
//  Created by Kinney Kare on 9/22/23.
//

import Foundation

struct DiscImageNames {
    // Define a dictionary to store companies and their discs
    static let companies: [String: [String: String]] = [
        "Infinite Discs": [
            "alpaca":"https://imagizer.imageshack.com/img922/2418/W4XnJX.png",
            "anubis":"https://imagizer.imageshack.com/img924/569/6gvgVj.png",
            "aztec":"https://imagizer.imageshack.com/img924/489/fdCE7i.png",
            "centurion":"https://imagizer.imageshack.com/img922/602/3pJnG2.png",
            "conqueror": "https://i.ibb.co/X4J89QD/Conq-removebg-preview.png",
            "chariot":"https://imagizer.imageshack.com/img924/1542/RoGDvm.png",
            "cohort":"https://imagizer.imageshack.com/img922/9666/Ak1jNE.png",
            "czar":"https://imagizer.imageshack.com/img924/8859/84mD5T.png",
            "dynasty":"https://imagizer.imageshack.com/img923/9766/0t41Vh.png",
            "emperor":"https://imagizer.imageshack.com/img924/5829/ouXTOV.png",
            "exodus":"https://imagizer.imageshack.com/img922/8889/RXhTha.png",
            "inca":"https://imagizer.imageshack.com/img924/8210/P1sD67.png",
            "kon-tiki":"https://imagizer.imageshack.com/img923/3780/HFvN78.png",
            "maya":"https://imagizer.imageshack.com/img924/1162/UINUNz.png",
            "myth":"https://imagizer.imageshack.com/img922/7906/7Z1wJA.png",
            "pharaoh":"https://imagizer.imageshack.com/img923/760/mg7Yh3.png",
            "ra":"https://imagizer.imageshack.com/img924/4161/zJZSif.png",
            "raze":"https://imagizer.imageshack.com/img923/2397/2Wvz4q.png",
            "roman":"https://imagizer.imageshack.com/img922/3958/eJWrOj.png",
            "ruin":"https://imagizer.imageshack.com/img923/356/nK5Nz4.png",
            "scarab":"https://imagizer.imageshack.com/img922/4884/9Wl2sJ.png",
            "scepter":"https://imagizer.imageshack.com/img923/8964/5dyKvb.png",
            "slab":"https://imagizer.imageshack.com/img923/7360/PN9WrL.png",
            "sphinx":"https://imagizer.imageshack.com/img924/1486/hc35ay.png",
            "tomb":"https://imagizer.imageshack.com/img923/2565/D6iEz4.png"
        ],
        "Clash Discs": [
            "berry":"https://imagizer.imageshack.com/img923/5803/JXm0hI.png",
            "butter":"https://imagizer.imageshack.com/img923/2118/XJ9OH5.png",
            "candy":"https://imagizer.imageshack.com/img924/6928/xQVmwc.png",
            "cinnamon":"https://imagizer.imageshack.com/img922/4460/mkfiBE.png",
            "cookie":"https://imagizer.imageshack.com/img923/4878/2LHpS1.png",
            "fudge":"https://imagizer.imageshack.com/img924/1483/wzZaLM.png",
            "ginger":"https://imagizer.imageshack.com/img922/3230/tzqKYG.png",
            "honey":"https://imagizer.imageshack.com/img922/2686/7AOE9f.png",
            "lotus":"https://imagizer.imageshack.com/img923/5320/pxwCew.png",
            "mango":"https://imagizer.imageshack.com/img924/504/E1QZ7i.png",
            "mint":"https://imagizer.imageshack.com/img923/2961/y0Mjh9.png",
            "peach":"https://imagizer.imageshack.com/img922/4282/geLTCt.png",
            "pepper":"https://imagizer.imageshack.com/img924/5648/cycXGB.png",
            "peppermint":"https://imagizer.imageshack.com/img922/3672/bX2TfD.png",
            "popcorn":"https://imagizer.imageshack.com/img923/2786/jiQZh9.png",
            "salt":"https://imagizer.imageshack.com/img924/3793/AznhrS.png",
            "soda":"https://imagizer.imageshack.com/img922/1124/M786QV.png",
            "spice":"https://imagizer.imageshack.com/img923/2144/q8Dizc.png",
            "vanilla":"https://imagizer.imageshack.com/img924/3615/Zgv8sp.png"
        ],
        "RPM": [
            "huia":"https://imagizer.imageshack.com/img923/8006/XGT1WV.png",
            "kahu":"https://imagizer.imageshack.com/img924/1383/U9St36.png",
            "kahu-os":"https://imagizer.imageshack.com/img923/3046/VyDnfE.png",
            "kahu-xg":"https://imagizer.imageshack.com/img922/3668/gdeMZc.png",
            "kea":"https://imagizer.imageshack.com/img923/1584/iyWRnY.png",
            "kiwi":"https://imagizer.imageshack.com/img924/1431/XCIfhc.png",
            "kotare":"https://imagizer.imageshack.com/img922/2058/mmhfoX.png",
            "kotuku":"https://imagizer.imageshack.com/img924/9471/YLcC3m.png",
            "pekapeka":"https://imagizer.imageshack.com/img923/1161/bgMfwF.png",
            "piwakawaka":"https://imagizer.imageshack.com/img923/7626/3Au62q.png",
            "ruru":"https://imagizer.imageshack.com/img922/8006/EXIVz8.png",
            "takapu":"https://imagizer.imageshack.com/img922/782/CTmoG2.png",
            "taniwha":"https://imagizer.imageshack.com/img924/6487/Rg4NMW.png",
            "tara-iti":"https://imagizer.imageshack.com/img922/9352/luZ6bd.png",
            "tui":"https://imagizer.imageshack.com/img922/9427/jvGizj.png"
        ],
        "DGA":  [
            "aftershock": "https://imagizer.imageshack.com/img922/4298/M8qfkC.png",
            "avalanche": "https://imagizer.imageshack.com/img924/8675/ADPLaK.png",
            "banzai": "https://imagizer.imageshack.com/img923/5310/IY5HXR.png",
            "blowfly": "https://imagizer.imageshack.com/img922/2730/E3Lxg8.png",
            "breaker": "https://imagizer.imageshack.com/img922/6444/vN4q9z.png",
            "gumbputt": "https://imagizer.imageshack.com/img923/9821/RHNyLS.png",
            "hellfire": "https://imagizer.imageshack.com/img924/4411/VEhQaw.png",
            "hurricane": "https://imagizer.imageshack.com/img923/1766/QhT9rR.png",
            "hypercane": "https://imagizer.imageshack.com/img924/8861/svfkvU.png",
            "pipeline": "https://imagizer.imageshack.com/img922/4491/0snXl3.png",
            "quake": "https://imagizer.imageshack.com/img923/3569/rgzpnn.png",
            "reef": "https://imagizer.imageshack.com/img923/8649/dzub94.png",
            "rift": "https://imagizer.imageshack.com/img922/8803/aRkS82.png",
            "riptide": "https://imagizer.imageshack.com/img922/2739/s1MZjs.png",
            "rogue": "https://imagizer.imageshack.com/img922/627/sQBt3Q.png",
            "sail": "https://imagizer.imageshack.com/img924/9341/4PgQaG.png",
            "shockwave": "https://imagizer.imageshack.com/img924/661/H2c8T1.png",
            "squall": "https://imagizer.imageshack.com/img922/5866/TuJMWm.png",
            "steady": "https://imagizer.imageshack.com/img924/8873/oIce1F.png",
            "steady-bl": "https://imagizer.imageshack.com/img922/7596/4rvYsL.png",
            "tempest": "https://imagizer.imageshack.com/img923/8900/5pgeZf.png",
            "titanic": "https://imagizer.imageshack.com/img922/1954/dxRCMi.png",
            "torrent": "https://imagizer.imageshack.com/img923/7277/wScCAI.png",
            "tremor": "https://imagizer.imageshack.com/img922/7624/XMPh1i.png",
            "tsunami": "https://imagizer.imageshack.com/img924/7311/JZymUp.png",
            "undertow": "https://imagizer.imageshack.com/img923/47/jCxpW1.png",
            "vortex": "https://imagizer.imageshack.com/img923/8645/5lUFGX.png"
        ],
        "Daredevil Discs": [
            "albatross": "https://imagizer.imageshack.com/img922/6216/KhH4UL.png",
            "beaver":"https://imagizer.imageshack.com/img922/9844/6J23iU.png",
            "big-horn":"https://imagizer.imageshack.com/img924/4267/coHrxA.png",
            "bigfoot": "https://imagizer.imageshack.com/img923/3521/2yv4Bj.png",
            "buffalo": "https://imagizer.imageshack.com/img922/3960/wlO8Os.png",
            "caribou": "https://imagizer.imageshack.com/img922/2001/ghybHW.png",
            "grizzly": "https://imagizer.imageshack.com/img924/3977/2xtm2y.png",
            "hellbender": "https://imagizer.imageshack.com/img922/4960/Wvhwkg.png",
            "hellbender-razorback": "https://imagizer.imageshack.com/img923/8267/cTH1zJ.png",
            "mammoth": "https://imagizer.imageshack.com/img923/6462/ql4ggG.png",
            "merlin": "https://imagizer.imageshack.com/img923/3097/C2R47m.png",
            "moose": "https://imagizer.imageshack.com/img923/1347/qtJ3pC.png",
            "ogopogo": "https://imagizer.imageshack.com/img924/4199/pZ3g7y.png",
            "owl": "https://imagizer.imageshack.com/img922/7885/SCYYfi.png",
            "polar-bear":"https://imagizer.imageshack.com/img922/7521/f5A3nF.png",
            "sabertooth": "https://imagizer.imageshack.com/img924/7082/XeRb3T.png",
            "sasquatch": "https://imagizer.imageshack.com/img923/7936/AiFf08.png",
            "swift-fox": "https://imagizer.imageshack.com/img924/3926/F4Hdly.png",
            "timberwolf": "https://imagizer.imageshack.com/img923/898/pjDxB7.png",
            "walrus": "https://imagizer.imageshack.com/img924/9999/RTq8b1.png",
            "woodchuck":"https://imagizer.imageshack.com/img922/9278/YqSyOa.png",
            "wolverine": "https://imagizer.imageshack.com/img923/4229/sbbUsU.png",
            "yeti": "https://imagizer.imageshack.com/img924/111/lXDVot.png"
        ],
        "MVP": [
            "amp":"https://imagizer.imageshack.com/img924/6941/G3Wyoh.png",
            "anode":"https://imagizer.imageshack.com/img923/9620/lbTfhi.png",
            "atom":"https://imagizer.imageshack.com/img924/1291/Ur8hBX.png",
            "axis":"https://imagizer.imageshack.com/img924/6828/UunWXA.png",
            "catalyst":"https://imagizer.imageshack.com/img922/9349/MZKyq4.png",
            "deflector":"https://imagizer.imageshack.com/img923/7343/4rPXsb.png",
            "dimension": "https://imagizer.imageshack.com/img924/2016/rd5ZYs.png",
            "energy": "https://imagizer.imageshack.com/img923/221/fwoGl8.png",
            "entropy": "https://imagizer.imageshack.com/img922/1640/uAji3L.png",
            "glitch": "https://imagizer.imageshack.com/img923/2356/REWapR.png",
            "impulse": "https://imagizer.imageshack.com/img922/6382/AJk1y6.png",
            "inertia": "https://imagizer.imageshack.com/img924/2009/X0w3yv.png",
            "ion": "https://imagizer.imageshack.com/img922/9325/G72xge.png",
            "limit": "https://imagizer.imageshack.com/img924/3819/pHFwQU.png",
            "matrix": "https://imagizer.imageshack.com/img922/4230/Q7hcYW.png",
            "motion": "https://imagizer.imageshack.com/img923/7729/roRwfH.png",
            "nitro": "https://imagizer.imageshack.com/img922/897/zFLMVI.png",
            "nomad": "https://imagizer.imageshack.com/img922/4165/oMweKX.png",
            "octane": "https://imagizer.imageshack.com/img924/8477/TIY5y3.png",
            "ohm": "https://imagizer.imageshack.com/img922/7348/nz7xdp.png",
            "orbital": "https://imagizer.imageshack.com/img924/7783/ZSU3M3.png",
            "particle": "https://imagizer.imageshack.com/img922/8858/so9Ssr.png",
            "phase": "https://imagizer.imageshack.com/img924/9431/fFBXoj.png",
            "photon": "https://imagizer.imageshack.com/img924/316/BEao0h.png",
            "reactor": "https://imagizer.imageshack.com/img923/8305/iU7Nyh.png",
            "relativity": "https://imagizer.imageshack.com/img923/7239/EVqh7c.png",
            "relay": "https://imagizer.imageshack.com/img924/1571/sU5ePa.png",
            "resistor": "https://imagizer.imageshack.com/img924/9327/KnHxRw.png",
            "servo": "https://imagizer.imageshack.com/img922/6669/isUVi3.png",
            "shock": "https://imagizer.imageshack.com/img924/9881/q6Lk0b.png",
            "signal": "https://imagizer.imageshack.com/img922/7793/vup7OG.png",
            "spin": "https://imagizer.imageshack.com/img924/8111/sH7v02.png",
            "switch": "https://imagizer.imageshack.com/img922/9646/boMJsC.png",
            "tangent": "https://imagizer.imageshack.com/img922/6560/VBpLpn.png",
            "teleport": "https://imagizer.imageshack.com/img923/2770/iNAFuP.png",
            "tensor": "https://imagizer.imageshack.com/img923/4442/UPu9nV.png",
            "terra": "https://imagizer.imageshack.com/img924/6991/vXp0Qk.png",
            "terra-electron": "https://imagizer.imageshack.com/img922/6120/0oAz4G.png",
            "tesla": "https://imagizer.imageshack.com/img923/2711/oEPrE1.png",
            "uplink": "https://imagizer.imageshack.com/img923/1542/lVOGDx.png",
            "vector": "https://imagizer.imageshack.com/img924/3513/t5doeZ.png",
            "vertex": "https://imagizer.imageshack.com/img922/7800/evZRqr.png",
            "volt":"https://imagizer.imageshack.com/img923/3183/l4JY1G.png",
            "watt": "https://imagizer.imageshack.com/img924/788/mG7JXA.png",
            "wave": "https://imagizer.imageshack.com/img923/562/2DksW7.png",
            "zenith": "https://imagizer.imageshack.com/img922/5575/x8cwQF.png"
        ],
        "Disc Golf UK": [
            "the-baron":"https://imagizer.imageshack.com/img923/3848/IQpwxK.png",
            "the-count":"https://imagizer.imageshack.com/img923/4467/w4FLdD.png",
            "the-duchess":"https://imagizer.imageshack.com/img924/6622/BUHa1i.png",
            "the-duke":"https://imagizer.imageshack.com/img922/534/DsbUJ5.png"
            
        ],
        "Elevation Disc Golf": [
            "arowana": "https://imagizer.imageshack.com/img924/4883/GF6Pl4.png",
            "binx-newcomer": "https://imagizer.imageshack.com/img922/2891/L7YI4G.png",
            "binx-ecoflex": "https://imagizer.imageshack.com/img922/7968/YKJtWy.png",
            "gecko":"https://imagizer.imageshack.com/img923/8159/ARWYIi.png",
            "interceptor":"https://imagizer.imageshack.com/img924/1706/MXlB3l.png",
            "koi":"https://imagizer.imageshack.com/img922/9048/PvEieo.png",
            "og-binx":"https://imagizer.imageshack.com/img924/2774/W0CrQA.png"
        ],
        "Axiom Discs": [
            "alias": "https://imagizer.imageshack.com/img923/726/5mtKlo.png",
            "clash": "https://imagizer.imageshack.com/img924/7365/EHNyhQ.png",
            "crave": "https://imagizer.imageshack.com/img922/8097/g4OQSN.png",
            "defy": "https://imagizer.imageshack.com/img923/3268/jEv4Cg.png",
            "delirium": "https://imagizer.imageshack.com/img924/2766/QiBcWc.png",
            "envy": "https://imagizer.imageshack.com/img922/1839/tgDBcT.png",
            "excite": "https://imagizer.imageshack.com/img923/8893/u8hfsP.png",
            "fireball": "https://imagizer.imageshack.com/img924/4710/OLgqJD.png",
            "hex": "https://imagizer.imageshack.com/img923/7524/RBmBto.png",
            "insanity": "https://imagizer.imageshack.com/img922/3973/AUK8m9.png",
            "inspire": "https://imagizer.imageshack.com/img924/2379/sWPrWT.png",
            "mayhem": "https://imagizer.imageshack.com/img923/7942/cydYAN.png",
            "panic": "https://imagizer.imageshack.com/img924/1356/eGYRlQ.png",
            "paradox": "https://imagizer.imageshack.com/img924/4989/VgyJcX.png",
            "proxy": "https://imagizer.imageshack.com/img924/9734/78aw2Q.png",
            "pyro": "https://imagizer.imageshack.com/img923/3528/xrM6kl.png",
            "rhythm": "https://imagizer.imageshack.com/img924/7606/4RxPE9.png",
            "tantrum": "https://imagizer.imageshack.com/img922/5659/e5jKEb.png",
            "tenacity": "https://imagizer.imageshack.com/img922/5341/weBfDz.png",
            "theory": "https://imagizer.imageshack.com/img923/5718/FTfyST.png",
            "thrill": "https://imagizer.imageshack.com/img924/6371/JmHufU.png",
            "time-lapse": "https://imagizer.imageshack.com/img922/9382/yIaI0T.png",
            "trance": "https://imagizer.imageshack.com/img923/7818/KbQyC3.png",
            "vanish": "https://imagizer.imageshack.com/img924/9472/NZeDFs.png",
            "virus": "https://imagizer.imageshack.com/img922/9262/bZ3pMN.png",
            "wrath": "https://imagizer.imageshack.com/img923/6576/i5hC2u.png"
        ],
        "Streamline": [
            "ascend": "https://imagizer.imageshack.com/img924/7803/If3tG5.png",
            "drift": "https://imagizer.imageshack.com/img923/1438/dWA93n.png",
            "echo": "https://imagizer.imageshack.com/img924/939/X4d21e.png",
            "electron-stabilizer": "https://imagizer.imageshack.com/img923/1893/YtUJtQ.png",
            "flare": "https://imagizer.imageshack.com/img924/9138/75m6GD.png",
            "jet": "https://imagizer.imageshack.com/img922/300/e8UKPD.png",
            "lift": "https://imagizer.imageshack.com/img924/8975/gH2cvS.png",
            "pilot": "https://imagizer.imageshack.com/img922/2904/03YVFC.png",
            "runway": "https://imagizer.imageshack.com/img923/8770/RS3cAp.png",
            "stabilizer": "https://imagizer.imageshack.com/img924/7586/AzfXIs.png",
            "trace": "https://imagizer.imageshack.com/img924/7531/vbl4Vh.png"
        ],
        "Dynamic Discs": [
            "agent": "https://imagizer.imageshack.com/img922/9760/IdgvQE.png",
            "bounty": "https://imagizer.imageshack.com/img922/5261/57HwyG.png",
            "breakout": "https://imagizer.imageshack.com/img923/5835/OdFdLH.png",
            "captain": "https://imagizer.imageshack.com/img923/8982/Y355TK.png",
            "convict": "https://imagizer.imageshack.com/img922/594/FAQ7cs.png",
            "criminal": "https://imagizer.imageshack.com/img923/1741/FNtwAq.png",
            "culprit": "https://imagizer.imageshack.com/img922/6107/xFdOSM.png",
            "defender": "https://imagizer.imageshack.com/img922/8490/osMRhL.png",
            "deputy": "https://imagizer.imageshack.com/img923/947/lqJ3IA.png",
            "emac-judge": "https://imagizer.imageshack.com/img922/598/KbrwEw.png",
            "enforcer": "https://imagizer.imageshack.com/img922/7573/vSX5wl.png",
            "escape": "https://imagizer.imageshack.com/img922/2110/suPSxI.png",
            "evader": "https://imagizer.imageshack.com/img924/6098/rAjLVG.png",
            "evidence": "https://imagizer.imageshack.com/img922/9233/CNbAnA.png",
            "felon": "https://imagizer.imageshack.com/img922/4655/A8RA6J.png",
            "freedom": "https://imagizer.imageshack.com/img924/7923/wPoBeC.png",
            "fugitive": "https://imagizer.imageshack.com/img923/1899/F4g2n3.png",
            "fugitive-supreme": "https://imagizer.imageshack.com/img924/1209/WsxYXs.png",
            "gavel": "https://imagizer.imageshack.com/img922/5351/1fgOIy.png",
            "getaway": "https://imagizer.imageshack.com/img924/8742/OLBVWh.png",
            "guard": "https://imagizer.imageshack.com/img924/5941/VWgT7c.png",
            "judge": "https://imagizer.imageshack.com/img923/6577/fHTN6k.png",
            "justice": "https://imagizer.imageshack.com/img923/9500/PXPZJI.png",
            "marshal": "https://imagizer.imageshack.com/img924/2291/MlhBaB.png",
            "maverick": "https://imagizer.imageshack.com/img923/508/1v5HjD.png",
            "patrol": "https://imagizer.imageshack.com/img923/846/C28xPm.png",
            "proof": "https://imagizer.imageshack.com/img922/2803/4QoIFp.png",
            "raider": "https://imagizer.imageshack.com/img923/7669/7NELa4.png",
            "renegade": "https://imagizer.imageshack.com/img922/9339/lnaN01.png",
            "sergeant": "https://imagizer.imageshack.com/img923/4144/yNvdLA.png",
            "sheriff": "https://imagizer.imageshack.com/img923/3054/PRCX9x.png",
            "slammer": "https://imagizer.imageshack.com/img922/1368/vXSV7y.png",
            "sockibomb-felon": "https://imagizer.imageshack.com/img924/707/CwZlR8.png",
            "sockibomb-slammer": "https://imagizer.imageshack.com/img922/9163/PQyHlE.png",
            "supreme-trespass": "https://imagizer.imageshack.com/img923/1792/OxLHpT.png",
            "suspect": "https://imagizer.imageshack.com/img923/8797/vo2vbD.png",
            "thief": "https://imagizer.imageshack.com/img922/3396/GPSNZv.png",
            "trespass": "https://imagizer.imageshack.com/img923/8594/1HcakT.png",
            "truth": "https://imagizer.imageshack.com/img922/9629/2M4QQP.png",
            "truth-emac": "https://imagizer.imageshack.com/img923/297/eED3Ik.png",
            "vandal": "https://imagizer.imageshack.com/img922/8386/RcCaPe.png",
            "verdict": "https://imagizer.imageshack.com/img924/2037/2n0f6r.png",
            "warant": "https://imagizer.imageshack.com/img924/4310/SiHyeQ.png",
            "warden": "https://imagizer.imageshack.com/img924/3586/iI6Wfn.png",
            "witness": "https://imagizer.imageshack.com/img922/6041/OmdsaK.png"
        ],
        "Latitude 64": [
            "anchor": "https://imagizer.imageshack.com/img924/7194/nMlC6n.png",
            "ballista": "https://imagizer.imageshack.com/img924/8448/y6h8uI.png",
            "ballista-pro": "https://imagizer.imageshack.com/img923/4877/2b9xzo.png",
            "beetle": "https://imagizer.imageshack.com/img923/5593/7abEv9.png",
            "bolt": "https://imagizer.imageshack.com/img924/7392/F23DmX.png",
            "bryce": "https://imagizer.imageshack.com/img923/7144/Js6KrS.png",
            "caltrop": "https://imagizer.imageshack.com/img924/1696/WiSEKZ.png",
            "claymore": "https://imagizer.imageshack.com/img923/4531/2iZzQN.png",
            "compass": "https://imagizer.imageshack.com/img923/3384/k6kD83.png",
            "core": "https://imagizer.imageshack.com/img924/3875/eDvlHy.png",
            "culverin": "https://imagizer.imageshack.com/img924/1423/XiFZgX.png",
            "cutlass": "https://imagizer.imageshack.com/img922/9075/bfJCKD.png",
            "dagger": "https://imagizer.imageshack.com/img924/2558/wNj2gJ.png",
            "diamond": "https://imagizer.imageshack.com/img924/8571/leFkYF.png",
            "explorer": "https://imagizer.imageshack.com/img924/3915/qjDYAH.png",
            "faith": "https://imagizer.imageshack.com/img923/3460/6NzlMA.png",
            "falchion": "https://imagizer.imageshack.com/img922/4249/CaiOT4.png",
            "flow": "https://imagizer.imageshack.com/img923/2772/T8HQl8.png",
            "fuji": "https://imagizer.imageshack.com/img922/5760/KCU74L.png",
            "fury": "https://imagizer.imageshack.com/img922/4752/JyPQXu.png",
            "fuse": "https://imagizer.imageshack.com/img922/8223/5eWakF.png",
            "gauntlet": "https://imagizer.imageshack.com/img923/1/hkMYhL.png",
            "gladiator": "https://imagizer.imageshack.com/img924/9708/DZauL0.png",
            "glory": "https://imagizer.imageshack.com/img923/234/tKk4CG.png",
            "gobi": "https://imagizer.imageshack.com/img922/14/2srs18.png",
            "grace": "https://imagizer.imageshack.com/img923/4617/SxahoQ.png",
            "halo": "https://imagizer.imageshack.com/img924/2563/AQfcfC.png",
            "havoc": "https://imagizer.imageshack.com/img923/5396/QOZpIK.png",
            "honor": "https://imagizer.imageshack.com/img922/3504/qJwxAT.png",
            "hope-royal-pro": "https://imagizer.imageshack.com/img923/1071/SlqRWQ.png",
            "jade": "https://imagizer.imageshack.com/img924/8049/uQWRWv.png",
            "keystone": "https://imagizer.imageshack.com/img922/2918/EnqOhb.png",
            "knight": "https://imagizer.imageshack.com/img924/5770/1oQtQA.png",
            "macana": "https://imagizer.imageshack.com/img924/5889/aPeJh1.png",
            "mace": "https://imagizer.imageshack.com/img922/5848/WjTkFI.png",
            "maul": "https://imagizer.imageshack.com/img924/7730/Pd2Drp.png",
            "mercy": "https://imagizer.imageshack.com/img922/8647/YbeThb.png",
            "missilen": "https://imagizer.imageshack.com/img924/2982/gaGGXE.png",
            "musket": "https://imagizer.imageshack.com/img924/5085/5FLCtI.png",
            "pearl": "https://imagizer.imageshack.com/img923/6706/ClABmf.png",
            "pioneer": "https://imagizer.imageshack.com/img922/8724/xjakhN.png",
            "pirate": "https://imagizer.imageshack.com/img923/3737/lnmLZt.png",
            "pure": "https://imagizer.imageshack.com/img922/6419/Sp4dnT.png",
            "raketen": "https://imagizer.imageshack.com/img923/7255/ndpctp.png",
            "recoil": "https://imagizer.imageshack.com/img924/3308/AFcoc2.png",
            "rive": "https://imagizer.imageshack.com/img923/1694/10lA6a.png",
            "river": "https://imagizer.imageshack.com/img923/5149/knmVwu.png",
            "river-pro": "https://imagizer.imageshack.com/img924/984/zoPZwh.png",
            "ruby": "https://imagizer.imageshack.com/img924/9770/yCatWG.png",
            "saint": "https://imagizer.imageshack.com/img924/6023/gOKDI1.png",
            "saint-pro": "https://imagizer.imageshack.com/img923/5917/DRcVuv.png",
            "sapphire": "https://imagizer.imageshack.com/img923/352/WpYupe.png",
            "sarek": "https://imagizer.imageshack.com/img922/4442/HCsPYi.png",
            "savior": "https://imagizer.imageshack.com/img924/3005/y6LjJ5.png",
            "scythe": "https://imagizer.imageshack.com/img923/3033/8xktbG.png",
            "sinus": "https://imagizer.imageshack.com/img923/4605/HLfcJX.png",
            "spark": "https://imagizer.imageshack.com/img922/6379/fv4P7w.png",
            "spike": "https://imagizer.imageshack.com/img924/7329/Pi8ioP.png",
            "stiletto": "https://imagizer.imageshack.com/img923/1097/UXGnU1.png",
            "striker": "https://imagizer.imageshack.com/img922/355/XDV6LT.png",
            "trust": "https://imagizer.imageshack.com/img924/1465/nA9kFm.png",
            "trident": "https://i.ibb.co/nDpSnk3/trident-lat64.png",
            "xxx": "https://imagizer.imageshack.com/img922/7489/9LeQLl.png",
            "zion": "https://imagizer.imageshack.com/img923/4927/JbVqFm.png"
        ],
        "Westside Discs": [
            "adder": "https://imagizer.imageshack.com/img923/4676/3uZCwa.png",
            "ahti": "https://imagizer.imageshack.com/img923/2344/5mpgdL.png",
            "anvil": "https://imagizer.imageshack.com/img923/9880/jyqvkH.png",
            "bard": "https://imagizer.imageshack.com/img922/9854/iXeaoP.png",
            "bear": "https://imagizer.imageshack.com/img924/6893/0At2QY.png",
            "boatman": "https://imagizer.imageshack.com/img922/5931/OOm248.png",
            "catapult": "https://imagizer.imageshack.com/img922/1928/pWkRz6.png",
            "crown": "https://imagizer.imageshack.com/img924/5845/6FDRX7.png",
            "destiny": "https://imagizer.imageshack.com/img924/9606/Z564wk.png",
            "fortress": "https://imagizer.imageshack.com/img924/1889/Gc2OAk.png",
            "gatekeeper": "https://imagizer.imageshack.com/img922/15/D8Qmid.png",
            "giant": "https://imagizer.imageshack.com/img923/9555/7tIT0K.png",
            "harp": "https://imagizer.imageshack.com/img924/5517/4J0j5l.png",
            "hatchet": "https://imagizer.imageshack.com/img924/4707/vo2srz.png",
            "king": "https://imagizer.imageshack.com/img923/8010/oVHyw1.png",
            "longbowman": "https://imagizer.imageshack.com/img924/6693/dlSbeD.png",
            "maiden": "https://imagizer.imageshack.com/img923/5224/Pfa1Jn.png",
            "northman": "https://imagizer.imageshack.com/img924/446/ZBqLKw.png",
            "pine": "https://imagizer.imageshack.com/img922/4912/NHzMM6.png",
            "queen": "https://imagizer.imageshack.com/img924/6798/3W2crM.png",
            "sampo": "https://imagizer.imageshack.com/img924/5909/oEnH9D.png",
            "seer": "https://imagizer.imageshack.com/img924/8949/pdlX14.png",
            "shield": "https://imagizer.imageshack.com/img924/3778/WwzQ3p.png",
            "sling": "https://imagizer.imageshack.com/img923/2964/2gk806.png",
            "sorcerer": "https://imagizer.imageshack.com/img922/6458/p9nqcx.png",
            "stag": "https://imagizer.imageshack.com/img923/5098/gNpDAq.png",
            "swan-1-reborn": "https://imagizer.imageshack.com/img924/3103/Z0In5K.png",
            "swan-2": "https://imagizer.imageshack.com/img922/9773/CglEi8.png",
            "sword": "https://imagizer.imageshack.com/img924/5139/6b5Iuo.png",
            "tursas": "https://imagizer.imageshack.com/img922/4443/cbVKjf.png",
            "underworld": "https://imagizer.imageshack.com/img923/1460/wIKq1E.png",
            "war-horse": "https://imagizer.imageshack.com/img924/7613/1ArfRo.png",
            "warship": "https://imagizer.imageshack.com/img922/3091/3F98VE.png",
            "world": "https://imagizer.imageshack.com/img922/6223/GqFt4x.png"
        ],
        "Disctroyer": [
            "dd-13-starling": "https://imagizer.imageshack.com/img923/9985/qeXatW.png",
            "fd-8-stork": "https://imagizer.imageshack.com/img922/9084/BcQmhT.png",
            "mr-5-skylark": "https://imagizer.imageshack.com/img924/5558/Pu1VtH.png",
            "nightjar": "https://imagizer.imageshack.com/img923/715/YGLtSR.png",
            "pa-3-sparrow": "https://imagizer.imageshack.com/img922/5999/UlKlhm.png"
        ],
        "Kastaplast": [
            "berg": "https://imagizer.imageshack.com/img924/2540/F1MEAR.png",
            "falk": "https://imagizer.imageshack.com/img924/3060/1QRDgl.png",
            "gote": "https://imagizer.imageshack.com/img924/8298/68e63Q.png",
            "grym": "https://imagizer.imageshack.com/img922/8827/YmN92R.png",
            "grym-x": "https://imagizer.imageshack.com/img922/5474/0YYYHA.png",
            "guld": "https://imagizer.imageshack.com/img923/5827/xL1cNn.png",
            "jarn": "https://imagizer.imageshack.com/img922/5228/v8RObH.png",
            "kaxe": "https://imagizer.imageshack.com/img923/6420/Fvc5OI.png",
            "kaxe-z": "https://imagizer.imageshack.com/img924/5641/7KuG3Y.png",
            "krut": "https://imagizer.imageshack.com/img924/5130/kechbH.png",
            "lots": "https://imagizer.imageshack.com/img924/4953/GMvbHt.png",
            "rask": "https://imagizer.imageshack.com/img922/5629/Kjadoz.png",
            "reko": "https://imagizer.imageshack.com/img923/7061/4ySwpx.png",
            "reko-x": "https://imagizer.imageshack.com/img922/4489/meElOZ.png",
            "stal": "https://imagizer.imageshack.com/img924/6523/5kVbVw.png",
            "stig": "https://imagizer.imageshack.com/img922/5905/7a8Jpm.png",
            "svea": "https://imagizer.imageshack.com/img924/6033/jXIptI.png",
            "vass": "https://imagizer.imageshack.com/img922/7815/HQ7Q3M.png"
        ],
        //TODO: Add the disc ether image to this list.
        "Gateway": [
            "apache":"https://imagizer.imageshack.com/img922/7610/Y7nJ7z.png",
            "apache-retooled":"https://imagizer.imageshack.com/img923/7330/sR3ShB.png",
            "apex":"https://imagizer.imageshack.com/img923/1294/dZiKqf.png",
            "assassin":"https://imagizer.imageshack.com/img922/5140/utmXg2.png",
            "blade":"https://imagizer.imageshack.com/img923/4615/UNWJWF.png",
            "blaze":"https://imagizer.imageshack.com/img924/4114/hcTPfu.png",
            "chief":"https://imagizer.imageshack.com/img924/2509/78CvSq.png",
            "chief-os":"https://imagizer.imageshack.com/img924/5515/pIY5VZ.png",
            "demon":"https://imagizer.imageshack.com/img923/6363/KNOTCw.png",
            "devil-hawk":"https://imagizer.imageshack.com/img924/9499/c5Ka53.png",
            "diablo": "https://imagizer.imageshack.com/img924/880/KFZpWJ.png",
            "diablo-dt": "https://imagizer.imageshack.com/img923/6061/FSgUHQ.png",
            "element": "https://imagizer.imageshack.com/img924/408/Lz8aes.png",
            "ether": "https://i.ibb.co/3Md8JFL/ether-gateway-discs.png",
            "g-one": "https://imagizer.imageshack.com/img922/9087/OQ2jPy.png",
            "houdini": "https://imagizer.imageshack.com/img923/6868/3yGXWC.png",
            "illusion": "https://imagizer.imageshack.com/img924/4626/WphNbo.png",
            "journey": "https://imagizer.imageshack.com/img922/535/wYjvmO.png",
            "karma": "https://imagizer.imageshack.com/img924/4327/j3vT7j.png",
            "magic": "https://imagizer.imageshack.com/img924/2910/F0ItjK.png",
            "mystic": "https://imagizer.imageshack.com/img923/3430/rCZfSh.png",
            "ninja": "https://imagizer.imageshack.com/img924/1551/KqzywU.png",
            "prophecy": "https://imagizer.imageshack.com/img922/8829/Gp4rk5.png",
            "rage": "https://imagizer.imageshack.com/img923/3114/6yvUeE.png",
            "realm": "https://i.ibb.co/zGn6JgR/realm-gateway.png",
            "sabre": "https://imagizer.imageshack.com/img922/2592/ElfNgr.png",
            "samurai": "https://imagizer.imageshack.com/img922/7197/6xlxT9.png",
            "scout": "https://imagizer.imageshack.com/img924/5609/umSDLI.png",
            "shaman": "https://imagizer.imageshack.com/img924/6163/jRSFYb.png",
            "slayer": "https://imagizer.imageshack.com/img924/5192/owlvWH.png",
            "spear": "https://imagizer.imageshack.com/img923/2011/GLo6UH.png",
            "speed-demon": "https://imagizer.imageshack.com/img924/3869/uHwBUi.png",
            "spell": "https://imagizer.imageshack.com/img922/6492/gBQ5TU.png",
            "spirit": "https://imagizer.imageshack.com/img922/5609/FWkqBZ.png",
            "voodoo": "https://imagizer.imageshack.com/img923/7291/CfNm14.png",
            "war-spear": "https://imagizer.imageshack.com/img923/4600/s6VA25.png",
            "warlock": "https://imagizer.imageshack.com/img924/6701/vcYaEX.png",
            "warrior-gateway": "https://imagizer.imageshack.com/img924/3452/xe02WQ.png",
            "wizard": "https://imagizer.imageshack.com/img924/3261/8gR1PM.png"
        ],
        "Sacred Discs": [
            "arrowhead":"https://imagizer.imageshack.com/img924/3594/rvUDbl.png",
            "gnome":"https://imagizer.imageshack.com/img922/4720/9fbQTV.png",
            "oracle":"https://imagizer.imageshack.com/img924/2188/vftt7h.png",
            "starship":"https://imagizer.imageshack.com/img924/1830/fkr0GA.png"
        ],
        "AquaFlight": [
            "dragonfly":"https://imagizer.imageshack.com/img924/1941/sxqypL.png",
            "osprey":"https://imagizer.imageshack.com/img922/6974/LTt6Kk.png",
            "peace-frog":"https://imagizer.imageshack.com/img923/9562/Df9Oe6.png",
            "pelican":"https://imagizer.imageshack.com/img922/4539/wqDu00.png",
            "swift":"https://imagizer.imageshack.com/img923/739/LkB78s.png"
        ],
        "Above Ground Level": [
            "baobab":"https://imagizer.imageshack.com/img922/3872/CMgGeE.png",
            "beech":"https://imagizer.imageshack.com/img922/4333/DhMkM8.png",
            "cedar":"https://imagizer.imageshack.com/img923/1379/RwVX1n.png",
            "douglas-fir":"https://imagizer.imageshack.com/img923/2956/guYiNY.png",
            "locust":"https://imagizer.imageshack.com/img923/8468/LJ4X2u.png",
            "madrone":"https://imagizer.imageshack.com/img922/7901/Ss5mfO.png",
            "magnolia":"https://imagizer.imageshack.com/img923/5725/HYXiPI.png",
            "manzanita":"https://imagizer.imageshack.com/img923/4905/uZDr3H.png",
            "ponderosa":"https://imagizer.imageshack.com/img924/1954/SxLVjp.png",
            "redwood":"https://imagizer.imageshack.com/img923/868/TA6QUs.png",
            "spruce":"https://imagizer.imageshack.com/img922/8233/tberCR.png",
            "sycamore":"https://imagizer.imageshack.com/img923/1925/hHLjOg.png"
        ],
        "Other": [
            "alpas":"https://imagizer.imageshack.com/img924/6664/wxSEAk.png",
            "andro-c":"https://imagizer.imageshack.com/img924/2176/FsIalF.png",
            "andro-c-retooled":"https://imagizer.imageshack.com/img922/3985/8BXIy7.png",
            "apollo":"https://imagizer.imageshack.com/img923/3202/GKDjOb.png",
            "brontosaurus":"https://imagizer.imageshack.com/img923/1024/Tu9k4a.png",
            "cypress":"https://imagizer.imageshack.com/img924/1214/fZekCK.png",
            "gila":"https://imagizer.imageshack.com/img922/9074/3No0G2.png",
            "golem":"https://imagizer.imageshack.com/img923/1511/kgB56E.png",
            "i-one":"https://imagizer.imageshack.com/img924/2739/ojkytV.png",
            "iridium":"https://imagizer.imageshack.com/img922/4670/Nda8me.png",
            "kgb":"https://imagizer.imageshack.com/img923/2755/UH7RSB.png",
            "kraken":"https://imagizer.imageshack.com/img922/372/ZoRBD3.png",
            "lawin":"https://imagizer.imageshack.com/img924/6979/VAdNmE.png",
            "leviathan":"https://imagizer.imageshack.com/img923/6978/Au2DKJ.png",
            "marvel":"https://imagizer.imageshack.com/img922/1077/rVik6a.png",
            "minotaur":"https://imagizer.imageshack.com/img923/5459/8YFhor.png",
            "narwhal":"https://imagizer.imageshack.com/img922/7276/JC4K8B.png",
            "nice":"https://imagizer.imageshack.com/img922/6302/GCzRuW.png",
            "scale":"https://imagizer.imageshack.com/img923/9059/kCu074.png",
            "serpent":"https://imagizer.imageshack.com/img924/5579/L8rOCy.png",
            "stego":"https://imagizer.imageshack.com/img922/6338/uPctTr.png",
            "strike":"https://imagizer.imageshack.com/img922/8189/IYiwT9.png",
            "tiyanak":"https://imagizer.imageshack.com/img923/5733/xinFhL.png",
            "tyrant":"https://imagizer.imageshack.com/img924/5279/5Eyc6M.png",
            "ultra":"https://imagizer.imageshack.com/img923/5605/gqVRHu.png",
            "white-widow":"https://imagizer.imageshack.com/img922/1460/3Rm3nZ.png",
            "zeal":"https://imagizer.imageshack.com/img924/2331/k6Xt0U.png"
        ],
        "Hooligan Discs": [
            "flip":"https://imagizer.imageshack.com/img924/8333/UL4GmT.png",
            "thread":"https://imagizer.imageshack.com/img924/5795/qnAUVS.png",
            "vibe":"https://imagizer.imageshack.com/img922/906/9ypFQv.png",
            "yeet":"https://imagizer.imageshack.com/img924/9509/jXyJD4.png"
        ],
        "Lone Star Discs": [
            "armadillo": "https://imagizer.imageshack.com/img924/4606/v2Mzvx.png",
            "artemis": "https://imagizer.imageshack.com/img922/6573/7fTtqr.png",
            "bb6": "https://imagizer.imageshack.com/img922/2325/Gf73Aa.png",
            "bearkat": "https://i.ibb.co/SNH6TSc/Bearkat-Lone-Star.png",
            "bayonet": "https://imagizer.imageshack.com/img923/7157/oqio5s.png",
            "benny": "https://imagizer.imageshack.com/img922/1204/yaKJPu.png",
            "bluebonnet": "https://imagizer.imageshack.com/img923/7272/iGAjED.png",
            "bowie": "https://imagizer.imageshack.com/img922/4315/e4JL20.png",
            "brazos": "https://imagizer.imageshack.com/img924/671/NSrXa8.png",
            "bull-snake": "https://imagizer.imageshack.com/img924/6955/kmrw1t.png",
            "chupacabra": "https://imagizer.imageshack.com/img924/5244/9sl2o7.png",
            "copperhead": "https://imagizer.imageshack.com/img923/3265/Cd3NRu.png",
            "crockett": "https://imagizer.imageshack.com/img923/5348/P2cPeQ.png",
            "curl": "https://imagizer.imageshack.com/img922/9921/uim0AE.png",
            "dos-x": "https://imagizer.imageshack.com/img923/737/Os9u2t.png",
            "frio": "https://imagizer.imageshack.com/img922/2034/QYuIQG.png",
            "growler": "https://i.ibb.co/ChTcWj0/Growler-Lone-Star.png",
            "guadalupe": "https://imagizer.imageshack.com/img923/9076/hP7ZV1.png",
            "harpoon": "https://imagizer.imageshack.com/img924/3334/phwkAr.png",
            "harrier": "https://imagizer.imageshack.com/img922/254/OqjEsk.png",
            "horny-toad": "https://i.ibb.co/wN1f0Pp/Horny-Toad-Lone-Star.png",
            "jack-rabbit": "https://imagizer.imageshack.com/img924/4646/XKftgX.png",
            "lariat": "https://imagizer.imageshack.com/img923/1254/8ICBPo.png",
            "lone-wolf": "https://imagizer.imageshack.com/img922/9122/faFATx.png",
            "mad-cat": "https://imagizer.imageshack.com/img923/6882/gQNHeM.png",
            "middy": "https://imagizer.imageshack.com/img924/350/EtTJ8s.png",
            "mockingbird": "https://imagizer.imageshack.com/img922/8638/sSpVF8.png",
            "nimitz": "https://imagizer.imageshack.com/img923/5374/AkGA7I.png",
            "penny-putter-premium": "https://imagizer.imageshack.com/img924/9109/W9SkTR.png",
            "penny-putter-victor": "https://imagizer.imageshack.com/img922/5348/it7MP0.png",
            "seguin": "https://imagizer.imageshack.com/img923/4777/5gvsgS.png",
            "texas-ranger": "https://imagizer.imageshack.com/img924/4851/8q6BAG.png",
            "the-dome": "https://imagizer.imageshack.com/img922/3958/vldzjW.png",
            "tombstone": "https://imagizer.imageshack.com/img924/2956/LXOrNN.png",
            "tumbleweed": "https://imagizer.imageshack.com/img924/6352/cQ4xcQ.png",
            "walker": "https://imagizer.imageshack.com/img923/4552/LiKy3A.png",
            "warbird": "https://imagizer.imageshack.com/img924/1946/GlsrAL.png"
        ],
        "Trash Panda": [
            "inner-core": "https://imagizer.imageshack.com/img923/575/AFlJwT.png",
            "dune": "https://imagizer.imageshack.com/img923/5674/6wS3Iy.png"
        ],
        "Co3": [
            "disc1": "https://example.com/co3/disc1",
            "disc2": "https://example.com/co3/disc2",
            "sharedDisc": "https://example.com/co3/sharedDisc"
        ]
    ]
    
    static func webLink(for company: String, disc: String) -> String? {
        return companies[company]?[disc]
    }
}


