///Users/kinneykare/Downloads/CRAVE_AXIOM DISCS.json
//  AnimationHelper.swift
//  DiscGolfSearch
//
//  Created by Kinney Kare on 1/26/24.
//

import Foundation


import Lottie
import UIKit

class AnimationHelper {
    
    static let shared = AnimationHelper()
    
    private let discURLs: [String: [String: String]] = [
        "Above Ground Level": [
            "baobab":"https://storage.googleapis.com/disc-animation/AboveGroundLevel/BAOBAB_ABOVE%20GROUND%20LEVEL.json",
            "beech":"https://storage.googleapis.com/disc-animation/AboveGroundLevel/BEECH_ABOVE%20GROUND%20LEVEL.json",
            "cedar":"https://storage.googleapis.com/disc-animation/AboveGroundLevel/CEDAR_ABOVE%20GROUND%20LEVEL.json",
           // "douglas-fir":"https://imagizer.imageshack.com/img923/2956/guYiNY.png",
            "locust":"https://storage.googleapis.com/disc-animation/AboveGroundLevel/LOCUST_ABOVE%20GROUND%20LEVEL.json",
            //"madrone":"https://imagizer.imageshack.com/img922/7901/Ss5mfO.png",
            "magnolia":"https://storage.googleapis.com/disc-animation/AboveGroundLevel/MAGNOLIA_ABOVE%20GROUND%20LEVEL.json",
            //"manzanita":"https://imagizer.imageshack.com/img923/4905/uZDr3H.png",
            //"ponderosa":"https://imagizer.imageshack.com/img924/1954/SxLVjp.png",
            "redwood":"https://storage.googleapis.com/disc-animation/AboveGroundLevel/REDWOOD_ABOVE%20GROUND%20LEVEL.json",
            "spruce":"https://storage.googleapis.com/disc-animation/AboveGroundLevel/SPRUCE_ABOVE%20GROUND%20LEVEL.json",
            "sycamore":"https://storage.googleapis.com/disc-animation/AboveGroundLevel/SYCAMORE_ABOVE%20GROUND%20LEVEL.json"
        ],
        "Axiom Discs": [
            "alias": "https://storage.googleapis.com/disc-animation/Axiom/ALIAS_AXIOM%20DISCS.json",
            "clash": "https://storage.googleapis.com/disc-animation/Axiom/CLASH_AXIOM%20DISCS.json",
            "crave": "https://storage.googleapis.com/disc-animation/Axiom/CRAVE_AXIOM%20DISCS.json",
            "defy": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_DEFY.json",
            //"delirium": "https://imagizer.imageshack.com/img924/2766/QiBcWc.png",
            //"envy": "https://imagizer.imageshack.com/img922/1839/tgDBcT.png",
            "excite": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_EXCITE.json",
            "fireball": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_FireBall.json",
            "hex": "https://storage.googleapis.com/disc-animation/Axiom/HEX_AXIOM%20DISCS.json",
            "insanity": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_INSANITY.json",
            "inspire": "https://storage.googleapis.com/disc-animation/Axiom/INSPIRE_AXIOM%20DISCS.json",
            "mayhem": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_MAYHEM.json",
            "panic": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_PANIC.json",
            "paradox": "https://storage.googleapis.com/disc-animation/Axiom/PARADOX_AXIOM%20DISCS.json",
           // "proxy": "",
            "pyro": "https://storage.googleapis.com/disc-animation/Axiom/PYRO_AXIOM%20DISCS.json",
            "rhythm": "https://storage.googleapis.com/disc-animation/Axiom/RHYTHM_AXIOM%20DISCS.json",
            "tantrum": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_TANTRUM.json",
            "tenacity": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_TENACITY.json",
            "theory": "https://storage.googleapis.com/disc-animation/Axiom/THEORY_AXIOM%20DISCS.json",
            "thrill": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_THRILL.json",
            "time-lapse": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_TIME-LAPSE.json",
            "trance": "https://storage.googleapis.com/disc-animation/Axiom/TRANCE_AXIOM%20DISCS.json",
            "vanish": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_VANISH.json",
            "virus": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_VIRUS.json",
            "wrath": "https://storage.googleapis.com/disc-animation/Axiom/AXIOM%20DISCS_WRATH.json"
        ],
        "Clash Discs": [
            "berry": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_BERRY.json",
            //"butter": "",
            //"candy": "",
            "cinnamon": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_CINNAMON.json",
            "cookie": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_COOKIE.json",
            //"fudge": "",
            "ginger": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_GINGER.json",
            "honey": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_HONEY.json",
            "lotus": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_LOTUS.json",
            "mango": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_MANGO.json",
            "mint": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_MINT.json",
            "peach": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_PEACH.json",
            "pepper": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_PEPPER.json",
            "peppermint": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_PEPPERMINT.json",
            //"popcorn": "",
            "salt": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_SALT.json",
            "soda": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_SODA.json",
            "spice": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_SPICE.json",
            "vanilla": "https://storage.googleapis.com/disc-animation/Clash%20Discs/Clash-Discs_VANILLA.json"
        ],
        "Daredevil Discs": [
            "albatross": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_ALBATROSS.json",
            //"beaver": "",
            //"big-horn": "",
            "bigfoot": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_BIGFOOT.json",
            "buffalo": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_BUFFALO.json",
            "caribou": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_CARIBOU.json",
            "grizzly": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_GRIZZLY.json",
            "hellbender": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_HELLBENDER.json",
            "hellbender-razorback": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_HELLBENDER%20(RAZORBACK).json",
            "mammoth": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_MAMMOTH.json",
            "merlin": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_MERLIN.json",
            "moose": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_MOOSE.json",
            "ogopogo": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_OGOPOGO.json",
           // "owl": "",
           // "polar-bear": "",
            "sabertooth": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_SABERTOOTH.json",
            "sasquatch": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_SASQUATCH.json",
            "swift-fox": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_SWIFT%20FOX.json",
            "timberwolf": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_SWIFT%20FOX.json",
            "walrus": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_TIMBERWOLF.json",
          //  "woodchuck": "",
            "wolverine": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_WOLVERINE.json",
            "yeti": "https://storage.googleapis.com/disc-animation/Daredevil%20Discs/Daredevil%20Discs_YETI.json"
        ],
        "DGA": [
            "aftershock": "https://storage.googleapis.com/disc-animation/DGA/DGA_AFTERSHOCK.json",
            "avalanche": "https://storage.googleapis.com/disc-animation/DGA/DGA_AVALANCHE.json",
            "banzai": "https://storage.googleapis.com/disc-animation/DGA/DGA_BANZAI.json",
            //"blowfly": "",
            //"breaker": "",
            //"gumbputt": "",
            "hellfire": "https://storage.googleapis.com/disc-animation/DGA/DGA_HELLFIRE.json",
            "hurricane": "https://storage.googleapis.com/disc-animation/DGA/DGA_HURRICANE.json",
            "hypercane": "https://storage.googleapis.com/disc-animation/DGA/DGA_HYPERCANE.json",
            "pipeline": "https://storage.googleapis.com/disc-animation/DGA/DGA_PIPELINE.json",
            "quake": "https://storage.googleapis.com/disc-animation/DGA/DGA_QUAKE.json",
            //"reef": "",
            "rift": "https://storage.googleapis.com/disc-animation/DGA/DGA_RIFT.json",
            "riptide": "https://storage.googleapis.com/disc-animation/DGA/DGA_RIPTIDE.json",
            "rogue": "https://storage.googleapis.com/disc-animation/DGA/DGA_ROGUE.json",
            "sail": "https://storage.googleapis.com/disc-animation/DGA/DGA_SAIL.json",
            "shockwave": "https://storage.googleapis.com/disc-animation/DGA/DGA_SHOCKWAVE.json",
            "squall": "https://storage.googleapis.com/disc-animation/DGA/DGA_SQUALL.json",
          //  "steady": "",
          //  "steady-bl": "",
            "tempest": "https://storage.googleapis.com/disc-animation/DGA/DGA_TEMPEST.json",
    //        "titanic": "",
            "torrent": "https://storage.googleapis.com/disc-animation/DGA/DGA_TORRENT.json",
            "tremor": "https://storage.googleapis.com/disc-animation/DGA/DGA_TREMOR.json",
            "tsunami": "https://storage.googleapis.com/disc-animation/DGA/DGA_TSUNAMI.json",
            "undertow": "https://storage.googleapis.com/disc-animation/DGA/DGA_UNDERTOW.json",
            "vortex": "https://storage.googleapis.com/disc-animation/DGA/DGA_VORTEX.json"
        ],
        
        "Discmania": [
            "astronaut": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_ASTRONAUT.json",
            "cd": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_CD.json",
            "cd1": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_CD1.json",
            "cd2": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_CD2.json",
            "cd3": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_CD3.json",
            "cloudbreaker": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_CLOUDBREAKER.json",
            //"dd": "",
            "dd-new": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_DD%20(NEW).json",
            "dd1": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_DD1.json",
            "dd2": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_DD2.json",
            //"dd3": "",
            "dd3-new": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_DD3%20(NEW).json",
            "ddx": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_DDX.json",
            "enigma": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_ENIGMA.json",
            "essence": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_ESSENCE.json",
           // "fd": "",
            "fd-new": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_FD%20(NEW).json",
            "fd1": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_FD1.json",
            "fd2": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_FD2.json",
            "fd3": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_FD3.json",
          //  "fox-spirit": "",
           // "gm": "",
           // "genius": "",
            "instinct": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_INSTINCT.json",
          //  "link": "",
          //  "logic": "",
            "md": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MD.json",
            "md1": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MD1.json",
            "md2": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MD2.json",
           // "md3": "",
            "md3-retooled": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MD3%20(RETOOLED).json",
            "md4": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MD4.json",
           // "md5": "",
            "md5-new": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MD5%20(NEW).json",
            "maestro": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MAESTRO.json",
            "magician": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MAGICIAN.json",
            "majesty": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MAJESTY.json",
            "mentor": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MENTOR.json",
            "mermaid": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MERMAID.json",
            "method": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_METHOD.json",
            "mutant": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_MUTANT.json",
            "origin": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_ORIGIN.json",
            //"p1": "",
           // "p1-new": "",
            //"p1x": "",
            //"p2": "",
            //"p2-new": "",
            //"p3": "",
            //"p3x": "",
           // "pd": "",
            "pd-new": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_PD%20(NEW).json",
            "pd2": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_PD2.json",
            "pd3": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_PD3.json",
            "pdx": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_PDX.json",
            "paradigm": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_PARADIGM.json",
          //  "rainmaker": "",
            "rockstar": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_ROCKSTAR.json",
          //  "sea-serpent": "",
        //    "sensei": "",
         //   "shogun": "",
            "splice": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_SPLICE.json",
        //    "spring-ox": "",
     //       "sun-bird": "",
            "td": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_TD.json",
            "td2": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_TD2.json",
            "tdx": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_TDX.json",
            "tactic": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_TACTIC.json",
            "tailor": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_TAILOR.json",
            "tilt": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_TILT.json",
            "vanguard": "https://storage.googleapis.com/disc-animation/Discmania/Discmania_VANGUARD.json"
        ], 
        "Discraft": [
            //"apx": "",
            "anax": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20ANAX.json",
            "archer": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20ANAX.json",
            "athena": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20ATHENA.json",
            "avenger": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20AVENGER.json",
            "avenger-ss": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20AVENGER%20SS.json",
          //  "banger-gt": "",
            "buzzz": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20BUZZZ.json",
            "buzzz-os": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20BUZZZ%20OS.json",
            "buzzz-ss": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20BUZZZ%20SS.json",
            "captains-raptor": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20CAPTAIN'S%20RAPTOR.json",
            //"challenger": "",
            //"challenger-os": "",
            //"challenger-ss": "",
            "cicada": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_CICADA.json",
            "comet": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20CAPTAIN'S%20RAPTOR.json",
            "crank": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20CRANK.json",
            "crank-ss": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20CRANK%20SS.json",
            "crush": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_CRUSH.json",
            "cyclone": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20CYCLONE.json",
            "drone": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20DRONE.json",
            //"fierce": "",
            "flash": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_FLASH.json",
            "flick": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_FLICK.json",
            //"focus": "",
            "force": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20FORCE.json",
            "glide": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_GLIDE.json",
            "hades": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20HADES.json",
            "hawk": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_HAWK.json",
            "heat": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_HEAT.json",
            "hornet": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_HORNET.json",
            "impact": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20IMPACT.json",
           // "luna": "",
            "machete": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_MACHETE.json",
            //"magnet": "",
            "malta": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_MALTA.json",
            "mantis": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20MANTIS.json",
            "meteor": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_METEOR.json",
            //"nebula": "",
            //"nuke": "",
            "nuke-os": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20NUKE%20OS.json",
            "nuke-ss": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20NUKE%20SS.json",
            "passion": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20PASSION.json",
            "predator": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20PREDATOR.json",
            "pulse": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20PULSE.json",
            "punisher": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20PUNISHER.json",
           // "puttr": "",
           // "raptor": "",
           // "rattler": "",
           // "reaper": "",
           // "ringer": "",
           // "ringer-gt": "",
           // "roach": "",
            "scorch": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20SCORCH.json",
           // "sol": "",
            "stalker": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20STALKER.json",
            "sting": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20STING.json",
            "stratus": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20STRATUS.json",
            //"surge": "",
           // "surge-ss": "",
            "talon": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20TALON.json",
            //"thrasher": "",
            "tracker": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20TRACKER.json",
            "undertaker": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20UNDERTAKER.json",
            "venom": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20VENOM.json",
            //"venom-retooled": "",
           // "vulture": "",
            "wasp": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20WASP.json",
            "wildcat": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20WILDCAT.json",
            "xl": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20XL.json",
            "xs": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20XS.json",
            "xpress": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20XPRESS.json",
           // "xtreme": "",
          //  "zeppelin": "",
          //  "zeus": "",
            "zombee": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20ZOMBEE.json",
            "zone": "https://storage.googleapis.com/disc-animation/Discraft/Discraft_%20ZONE.json",
           // "zone-os": ""
        ],
        
        "Dynamic Discs": [
          //  "agent": "",
            "bounty": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_BOUNTY.json",
            "breakout": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_BREAKOUT.json",
            "captain": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_Captain.json",
            "convict": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_CONVICT.json",
            "criminal": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_CRIMINAL.json",
            "culprit": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_CULPRIT.json",
            "defender": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_DEFENDER.json",
           // "deputy": "",
           // "emac-judge": "",
            "enforcer": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_ENFORCER.json",
            "escape": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_%20ESCAPE.json",
            "evader": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_EVADER.json",
            "evidence": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_EVIDENCE.json",
            "felon": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_FELON.json",
            "freedom": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_FREEDOM.json",
            "fugitive": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_FUGITIVE.json",
            "fugitive-supreme": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_FUGITIVE%20(SUPREME).json",
           // "gavel": "",
            "getaway": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_GETAWAY.json",
           // "guard": "",
           // "judge": "",
            "justice": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_JUSTICE.json",
           // "marshal": "",
            "maverick": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_MAVERICK.json",
          //  "patrol": "",
            "proof": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_PROOF.json",
            "raider": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_RAIDER.json",
            "renegade": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_RENEGADE.json",
            "sergeant": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_Sargent.json",
            "sheriff": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_SHERIFF.json",
         //   "slammer": "",
            "sockibomb-felon": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_SOCKIBOMB%20FELON.json",
          //  "sockibomb-slammer": "",
            "supreme-emac-truth": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_SUPREME%20EMAC%20TRUTH.json",
            "supreme-trespass": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_SUPREME%20TRESPASS.json",
            "suspect": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_SUSPECT.json",
            "thief": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_THIEF.json",
            "trespass": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_TRESPASS.json",
            "truth": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_TRUTH.json",
            "truth-emac": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_TRUTH%2C%20EMAC.json",
            "vandal": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_VANDAL.json",
            "verdict": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_VERDICT.json",
            "warant": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_WARANT.json",
         //   "warden": "",
            "witness": "https://storage.googleapis.com/disc-animation/Dynamic-Discs/Dynamic-Discs_WITNESS.json"
    ],
        "Elevation Disc Golf": [
         //   "arowana": "",
            "binx-newcomer": "https://storage.googleapis.com/disc-animation/Elevation-%20Disc-%20Golf/Elevation-Disc-Golf_BINX%2C%20NEWCOMER.json",
            "binx-ecoflex": "https://storage.googleapis.com/disc-animation/Elevation-%20Disc-%20Golf/Elevation-Disc-Golf_BINX%2C%20ECOFLEX.json",
            "gecko": "https://storage.googleapis.com/disc-animation/Elevation-%20Disc-%20Golf/Elevation-Disc-Golf_GECKO.json",
            "interceptor": "https://storage.googleapis.com/disc-animation/Elevation-%20Disc-%20Golf/Elevation-Disc-Golf_OG%20BINX.json",
           // "koi": "",
            "og-binx": "https://storage.googleapis.com/disc-animation/Elevation-%20Disc-%20Golf/Elevation-Disc-Golf_OG%20BINX.json"
        ],
        
        "Finish Line": [
            "daytona":"https://storage.googleapis.com/disc-animation/Finish%20Line/Finish%20Line_DAYTONA.json",
            "era":"https://storage.googleapis.com/disc-animation/Finish%20Line/Finish%20Line_ERA.json",
            "interval":"https://storage.googleapis.com/disc-animation/Finish%20Line/Finish%20Line_INTERVAL.json",
           // "pace":"",
            "rally":"https://storage.googleapis.com/disc-animation/Finish%20Line/Finish%20Line_RALLY.json",
            "supra":"https://storage.googleapis.com/disc-animation/Finish%20Line/Finish%20Line_SUPRA.json",
            "torque":"https://storage.googleapis.com/disc-animation/Finish%20Line/Finish%20Line_TORQUE.json"
        ],
        
        "Gateway": [
            "apache": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_APACHE.json",
            "apache-retooled": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_APACHE%20(RETOOLED).json",
            "apex": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_APEX.json",
            "assassin": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_ASSASSIN.json",
            "blade": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_BLADE.json",
            "blaze": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_BLAZE.json",
        //    "chief": "",
         //   "chief-os": "",
            "demon": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_DEMON.json",
        //   "devil-hawk": "",
            "diablo": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_DIABLO.json",
            "diablo-dt": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_DIABLO%20DT.json",
            "ether": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_ETHER.json",
            "element": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_ELEMENT.json",
            "g-one": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_G-ONE.json",
         //   "houdini": "",
            "illusion": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_ILLUSION.json",
            "journey": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_JOURNEY.json",
            "karma": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_KARMA.json",
         //   "magic": "",
            "mystic": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_MYSTIC.json",
            "ninja": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_NINJA.json",
            "prophecy": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_PROPHECY.json",
            "rage": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_RAGE.json",
            "realm":"https://storage.googleapis.com/disc-animation/Gateway/Gateway_REALM.json",
            "sabre": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_SABRE.json",
            "samurai": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_SAMURAI.json",
            "scout": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_SCOUT.json",
          //  "shaman": "",
            "slayer": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_SLAYER.json",
            "spear": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_SPEAR.json",
            "speed-demon": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_SPEED%20DEMON.json",
            "spell": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_SPELL.json",
            "spirit": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_SPIRIT.json",
         //   "voodoo": "",
         //   "war-spear": "",
          //  "warlock": "",
            "warrior-gateway": "https://storage.googleapis.com/disc-animation/Gateway/Gateway_WARRIOR%20(GATEWAY).json",
           // "wizard": ""
        ],
        "Infinite Discs": [
            //"alpaca": "",
            "anubis": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_ANUBIS.json",
            "aztec": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_%20AZTEC.json",
            "centurion": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_CENTURION.json",
            "chariot": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_%20CHARIOT.json",
            //"cohort": "",
            "conqueror": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_CONQUEROR.json",
            "czar": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_CZAR.json",
            "dynasty": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_DYNASTY.json",
            "emperor": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_EMPEROR.json",
            "exodus": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_EXODUS.json",
            "inca": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_INCA.json",
            "kon-tiki": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_KON%20TIKI.json",
            "maya": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_MAYA.json",
            //"myth": "",
            "pharaoh": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_PHARAOH.json",
            "ra": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_RA.json",
            //"raze": "",
            "roman": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_%20ROMAN.json",
            //"ruin": "",
            //"scarab": "",
            "scepter": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_SCEPTER.json",
            "slab": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_SLAB.json",
            "sphinx": "https://storage.googleapis.com/disc-animation/Infinite-%20Discs/Infinite-Discs_SPHINX.json",
           // "tomb": ""
        ],
        "Innova": [
          //  "aero": "",
            "alien": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20ALIEN.json",
          //  "animal": "",
            "ape": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20APE.json",
            "archangel": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20ARCHANGEL.json",
          //  "archon": "",
         //   "atlas": "",
          //  "avatar": "",
          //  "aviar": "",
           // "aviar-classic": "",
         //   "aviar-driver": "",
         //   "aviar3": "",
           // "aviarx3": "",
          //  "banshee": "",
            "beast": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20BEAST.json",
            "boss": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20BOSS.json",
          //  "bullfrog": "",
          //  "caiman": "",
            "charger": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20CHARGER.json",
          //  "cheetah": "",
           // "classic-roc": "",
            "cobra": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20COBRA.json",
            "colossus": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20COLOSSUS.json",
           // "colt": "",
            "corvette": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20CORVETTE.json",
           // "coyote": "",
            "cro": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20CRO.json",
            "croc": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20CROC.json",
            "daedalus": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20DAEDALUS.json",
           // "dart": "",
            "destroyer": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20DESTROYER.json",
            "dominator": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20DOMINATOR.json",
            "dragon": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20DRAGON.json",
            "eagle": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20EAGLE.json",
            "fl": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20FL.json",
            "fairway-disc": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20FAIRWAY%20DISC.json",
            "firebird": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20FIREBIRD.json",
            //"firefly": "",
            "firestorm": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20FIRESTORM.json",
            "foxbat": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20FOXBAT.json",
           // "gator": "",
           // "gator3": "",
            "gazelle": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20GAZELLE.json",
            "groove": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20GROOVE.json",
            "hawkeye": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20HAWKEYE.json",
           // "hydra": "",
            "it": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20IT.json",
           // "invader": "",
            "invictus": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20INVICTUS.json",
           // "jk-aviar": "",
            "jay": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20JAY.json",
            "juggernaut": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20JUGGERNAUT.json",
            //"kc-aviar": "",
            "katana": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20KATANA.json",
            //"khan": "",
            "krait": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20KRAIT.json",
            //"leopard": "",
            "leopard3": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20LEOPARD3.json",
            "lion": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20LION.json",
            "mako": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20MAKO.json",
            "mako3": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20MAKO3.json",
           // "mamba": "",
            "manta": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20MANTA.json",
            //"max": "",
            "mid-disc3": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20MID-DISC3.json",
            //"mirage": "",
            "monarch": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20MONARCH.json",
            "mystere": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20MYSTERE.json",
           // "nova": "",
            "orc": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20ORC.json",
            "panther": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20PANTHER.json",
           // "pig": "",
           // "polecat": "",
           // "power-disc": "",
            "power-disc2": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20POWER%20DISC2.json",
            //"python": "",
            "ram": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20RAM.json",
            "rat": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20RAT.json",
           // "rhyno": "",
            "roadrunner": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20ROADRUNNER.json",
            //"roc": "",
            "roc-x3": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20ROC%20X3.json",
            "roc3": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20ROC3.json",
            //"rollo": "",
            "savant": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20SAVANT.json",
            //"scorpion": "",
            "shark": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20SHARK.json",
            "shark3": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20SHARK3.json",
            "shryke": "https://storage.googleapis.com/disc-animation/Innova/Innova_%20SHRYKE.json",
            //"sidewinder": "",
            //"skeeter": "",
            //"sonic": "",
            //"spider": "",
            //"starfire": "",
            //"starfire-l": "",
            //"stingray": "",
            //"stud": "",
            //"tl": "",
            //"tl3": "",
            //"teerex": "",
            //"teebird": "",
            //"teebird3": "",
            //"teedevil": "",
            //"tern": "",
            //"thunderbird": "",
            //"toro": "",
            //"vcobra": "",
            //"vroc": "",
            //"valkyrie": "",
            //"viking": "",
            //"viper": "",
            //"vulcan": "",
            //"wahoo": "",
            //"wedge": "",
            //"whale": "",
            //"whippet": "",
            //"wolf": "",
            //"wombat": "",
            //"wombat3": "",
            //"wraith": "",
            //"xcaliber": "",
            //"xd": "",
            //"xero": "",
            //"yeti-aviar": "",
            //"zephyr": ""
        ],
        "Latitude 64": [
            "anchor": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20ANCHOR.json",
          //  "ballista": "",
          //  "ballista-pro": "",
            //"beetle": "",
          //  "bolt": "",
          //  "bryce": "",
           // "caltrop": "",
            "claymore": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20CLAYMORE.json",
            "compass": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_COMPASS.json",
            "core": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20CORE.json",
           // "culverin": "",
           // "cutlass": "",
           // "dagger": "",
            "diamond": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_DIAMOND.json",
            "explorer": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20EXPLORER.json",
           // "faith": "",
            "falchion": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20FALCHION.json",
           // "flow": "",
            "fuji": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20FUJI.json",
           // "fury": "",
            "fuse": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20FUSE.json",
          //  "gauntlet": "",
           // "gladiator": "",
            "glory": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20GLORY.json",
            "gobi": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20GOBI.json",
         //   "grace": "",
          //  "halo": "",
         //   "havoc": "",
          //  "honor": "",
          //  "hope-royal-pro": "",
          //  "jade": "",
          //  "keystone": "",
          //  "knight": "",
          //  "macana": "",
          //  "mace": "",
            "maul": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20MAUL.json",
           // "mercy": "",
          //  "missilen": "",
           // "musket": "",
            "pearl": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20PEARL.json",
           // "pioneer": "",
            "pirate": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20PIRATE.json",
          //  "pure": "",
          //  "raketen": "",
           // "recoil": "",
           // "rive": "",
            "river": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20RIVER.json",
            "river-pro": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20RIVER%20PRO.json",
           // "ruby": "",
           // "saint": "",
            "saint-pro": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20SAINT%20PRO.json",
          //  "sapphire": "",
           // "sarek": "",
            "savior": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_SAVIOR.json",
         //   "scythe": "",
          //  "sinus": "",
            "spark": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20SPARK.json",
          //  "spike": "",
           // "stiletto": "",
            "striker": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20STRIKER.json",
            "trident": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20TRIDENT.json",
            "trust": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_TRUST.json",
            "xxx": "https://storage.googleapis.com/disc-animation/Latitude-%2064/Latitude-64_%20XXX.json",
        //    "zion": ""
        ],
        "Lightning": [
            "1-driver": "https://storage.googleapis.com/disc-animation/Lightening%20/Lightning_%20DRIVER.json",
            "1-flyer": "https://storage.googleapis.com/disc-animation/Lightening%20/Lightning_%20FLYER.json",
            "1-helix": "https://storage.googleapis.com/disc-animation/Lightening%20/Lightning_%20HELIX.json",
            "1-hookshot": "https://storage.googleapis.com/disc-animation/Lightening%20/Lightning_HOOKSHOT.json",
            "1-hyzer": "https://storage.googleapis.com/disc-animation/Lightening%20/Lightning_%20HYZER.json"
        ],
        "Lone Star Discs": [
           // "armadillo": "",
            "artemis": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_ARTEMIS.json",
            "bb6": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_BB6.json",
            //"bayonet": "",
            "bearkat": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_BEARKAT.json",
           // "benny": "",
           // "bluebonnet": "",
            //"bowie": "",
            "brazos": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_BRAZOS.json",
            //"bull-snake": "",
            "chupacabra": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_CHUPACABRA.json",
           // "copperhead": "",
           // "crockett": "",
            "curl": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_CURL.json",
            "dos-x": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_DOS%20X.json",
            "frio": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_FRIO.json",
            "growler": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_GROWLER.json",
            "guadalupe": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_GUADALUPE.json",
            "harpoon": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_HARPOON.json",
           // "harrier": "",
            "horny-toad": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_HORNY%20TOAD.json",
            //"jack-rabbit": "",
            "lariat": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_LARIAT.json",
            "lone-wolf": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_LONE%20WOLF.json",
            "mad-cat": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_MAD%20CAT.json",
            "middy": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_MIDDY.json",
            "mockingbird": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_MOCKINGBIRD.json",
            "nimitz": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_NIMITZ.json",
            //"penny-putter-premium": "",
           // "penny-putter-victor": "",
            //"seguin": "",
            "texas-ranger": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_TEXAS%20RANGER.json",
            "the-dome": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_THE%20DOME.json",
          //  "tombstone": "",
            "tumbleweed": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_TUMBLEWEED.json",
            "walker": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_WALKER.json",
            "warbird": "https://storage.googleapis.com/disc-animation/Lone-%20Star-%20Discs/Lone-Star-Discs_WARBIRD.json"
        ],
        "Millennium": [
           // "aquarius": "",
          //  "aries": "",
            "astra": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_ASTRA.json",
            "astra-x": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20ASTRA-X.json",
            "auroraqms": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_AURORAQMS.json",
            "draco": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_DRACO.json",
            "falcon": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20FALCON.json",
            "helio-vela": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20HELIO%20VELA.json",
            "jls": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20JLS.json",
          //  "marksman": "",
            "moab": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20MOAB.json",
            "mortar": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20MORTAR.json",
          //  "omega": "",
            //"omega-big-bead": "",
          //  "omega4": "",
            "orion-lf": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_ORION%20LF.json",
            "orion-ls": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_ORION%20LS.json",
            "polaris-lf": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20POLARIS%20LF.json",
            "polaris-ls": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20POLARIS%20LS.json",
            "quasar": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20QUASAR.json",
            "sabot": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_SABOT.json",
            "scorpius": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20SCORPIUS.json",
            "sentinel": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20SENTINEL.json",
            "solstice": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20SOLSTICE.json",
         //   "tank": "",
            "taurus": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_TAURUS.json",
            "vela": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_%20VELA.json",
            "veteran": "https://storage.googleapis.com/disc-animation/Millennium%20/Millennium_VETERAN.json"
        ],
        "Other": [
           // "alpas": "",
            "andro-c": "https://storage.googleapis.com/disc-animation/Other/Other_ANDRO%20C.json",
            "andro-c-retooled": "https://storage.googleapis.com/disc-animation/Other/Other_ANDRO%20C%20(RETOOLED).json",
            "apollo": "https://storage.googleapis.com/disc-animation/Other/Other_APOLLO.json",
            "brontosaurus": "https://storage.googleapis.com/disc-animation/Other/Other_BRONTOSAURUS.json",
            "cypress": "https://storage.googleapis.com/disc-animation/Other/Other_CYPRESS.json",
            "gila": "https://storage.googleapis.com/disc-animation/Other/Other_GILA.json",
            "golem": "https://storage.googleapis.com/disc-animation/Other/Other_GOLEM.json",
            "i-one": "https://storage.googleapis.com/disc-animation/Other/Other_I-ONE.json",
           // "iridium": "",
            "kgb": "https://storage.googleapis.com/disc-animation/Other/Other_KGB.json",
            "kraken": "https://storage.googleapis.com/disc-animation/Other/Other_KRAKEN.json",
            "lawin": "https://storage.googleapis.com/disc-animation/Other/Other_LAWIN.json",
            "leviathan": "https://storage.googleapis.com/disc-animation/Other/Other_LEVIATHAN.json",
           // "marvel": "",
            "minotaur": "https://storage.googleapis.com/disc-animation/Other/Other_MINOTAUR.json",
            //"narwhal": "",
            "nice": "https://storage.googleapis.com/disc-animation/Other/Other_NICE!.json",
            "pure-og": "https://storage.googleapis.com/disc-animation/Other/Other_PURE%20OG.json",
           // "scale": "",
            //"serpent": "",
          //  "stego": "",
            "strike": "https://storage.googleapis.com/disc-animation/Other/Other_STRIKE.json",
            "tiyanak": "https://storage.googleapis.com/disc-animation/Other/Other_TIYANAK.json",
            "tyrant": "https://storage.googleapis.com/disc-animation/Other/Other_TYRANT.json",
            "ultra": "https://storage.googleapis.com/disc-animation/Other/Other_ULTRA.json",
        //    "white-widow": "",
          //  "zeal": ""
          ],
        "RPM": [
            "huia": "https://storage.googleapis.com/disc-animation/RPM/RPM_HUIA.json",
            "kahu": "https://storage.googleapis.com/disc-animation/RPM/RPM_KAHU.json",
            //"kahu-os": "",
            "kahu-xg": "https://storage.googleapis.com/disc-animation/RPM/RPM_KAHU%20XG.json",
            "kea": "https://storage.googleapis.com/disc-animation/RPM/RPM_KEA.json",
            "kiwi": "https://storage.googleapis.com/disc-animation/RPM/RPM_KIWI.json",
            "kotare": "https://storage.googleapis.com/disc-animation/RPM/RPM_KOTARE.json",
            "kotuku": "https://storage.googleapis.com/disc-animation/RPM/RPM_KOTUKU.json",
            "pekapeka": "https://storage.googleapis.com/disc-animation/RPM/RPM_PEKAPEKA.json",
            "piwakawaka": "https://storage.googleapis.com/disc-animation/RPM/RPM_PIWAKAWAKA.json",
          //  "ruru": "",
          //  "takapu": "",
            "taniwha": "https://storage.googleapis.com/disc-animation/RPM/RPM_TANIWHA.json",
            "tara-iti": "https://storage.googleapis.com/disc-animation/RPM/RPM_TARA%20ITI.json",
           // "tui": ""
          ],
        "Streamline": [
            "ascend": "https://storage.googleapis.com/disc-animation/Streamline/Streamline_ASCEND.json",
            "drift": "https://storage.googleapis.com/disc-animation/Streamline/Streamline_DRIFT.json",
            "echo": "https://storage.googleapis.com/disc-animation/Streamline/Streamline_ECHO.json",
           // "electron-stabilizer": "",
           // "flare": "",
            "jet": "https://storage.googleapis.com/disc-animation/Streamline/Streamline_JET.json",
            "lift": "https://storage.googleapis.com/disc-animation/Streamline/Streamline_LIFT.json",
           // "pilot": "",
            "runway": "https://storage.googleapis.com/disc-animation/Streamline/Streamline_RUNWAY.json",
            //"stabilizer": "",
            "trace": "https://storage.googleapis.com/disc-animation/Streamline/Streamline_%20TRACE.json"
          ]
        
    ]
    
    private init() {}
        
    func setupFlightPathAnimationView(currentDisc: DiscGolfDisc, discCompanyName: String, discName: String, animationView: LottieAnimationView) {
            // Check if the disc company and disc name exist in the dictionary
            guard let companyDiscs = discURLs[discCompanyName],
                  let url = companyDiscs[discName] else {
                // Handle the case when the combination of disc company and disc name is not found
                getFlightPathImageFromLink(disc: currentDisc) { image in
                    // Show the default image if provided
                    let imageView = UIImageView(image: image)
                    imageView.frame = animationView.bounds
                    animationView.addSubview(imageView)
                }
                return
            }
            
            // Load and play the animation using the obtained URL
            guard let animationURL = URL(string: url) else { return }
            DispatchQueue.main.async {
                LottieAnimation.loadedFrom(url: animationURL, closure: { animation in
                    animationView.animation = animation
                    animationView.contentMode = .scaleAspectFit
                    animationView.loopMode = .loop
                    animationView.animationSpeed = 1.5
                    animationView.play()
                }, animationCache: DefaultAnimationCache.sharedCache)
            }
        }
    
    private func getFlightPathImageFromLink(disc: DiscGolfDisc, completion: @escaping (UIImage?) -> Void) {
        let weblink = disc.pic
        if let imageURL = URL(string: weblink) {
            APIManager.shared.downloadImage(from: imageURL) { imageData in
                DispatchQueue.main.async {
                    if let imageData = imageData, let image = UIImage(data: imageData) {
                        completion(image)
                    } else {
                        print("Failed to create UIImage from image data")
                        completion(UIImage(named: "noFlightPath"))
                    }
                }
            }
        } else {
            DispatchQueue.main.async {
                print("Failed to create URL from web link")
                completion(UIImage(named: "noFlightPath"))
            }
        }
    }
    
    }
